`timescale 1ns/1ps 
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Jan  7 2024 20:15:16 WET (Jan  7 2024 20:15:16 UTC)

// Verification Directory fv/main 

module main(CLK, RST, bist_start, bist_end, pass_fail, in_k, in_j,
     in_en, out_synced_d, out_sync_err_d);
  input CLK, RST, bist_start, in_k, in_j, in_en;
  output bist_end, pass_fail, out_synced_d, out_sync_err_d;
  wire CLK, RST, bist_start, in_k, in_j, in_en;
  wire bist_end, pass_fail, out_synced_d, out_sync_err_d;
  wire [2:0] circuito_scan_fs_state;
  wire [23:0] hf;
  wire [6:0] Bist_count_M;
  wire [6:0] Bist_count_N;
  wire [2:0] Bist_state;
  wire Bist_n_1058, Bist_n_1059, Bist_n_1060, Bist_n_1062, Bist_n_1064,
       Bist_n_1069, Bist_n_1070, Bist_n_1071;
  wire Bist_n_1084, Bist_n_1089, Bist_n_1129, Bist_n_1132, Bist_n_1141,
       LFSR_in2_x3, LFSR_in2_x_46, LFSR_in2_x_47;
  wire LFSR_in_x3, MISR_h0, MISR_h1, MISR_h2, MISR_h3, MISR_h4,
       MISR_h5, MISR_h6;
  wire MISR_h7, MISR_h8, MISR_h9, MISR_h10, MISR_h11, MISR_h12,
       MISR_h14, MISR_h15;
  wire MISR_h17, MISR_h18, MISR_h19, MISR_h20, MISR_h21, MISR_h22,
       MISR_h23, Seed;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34,
       UNCONNECTED35, UNCONNECTED36, UNCONNECTED37, UNCONNECTED38;
  wire UNCONNECTED39, UNCONNECTED40, UNCONNECTED41, UNCONNECTED42,
       UNCONNECTED43, UNCONNECTED44, UNCONNECTED45, UNCONNECTED46;
  wire UNCONNECTED47, UNCONNECTED48, UNCONNECTED49, UNCONNECTED50,
       UNCONNECTED51, circuito_scan_n_0, circuito_scan_n_1,
       circuito_scan_n_10;
  wire circuito_scan_n_17, circuito_scan_n_19, in_x0, in_x1, in_x2,
       n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_81, n_82;
  wire n_83, n_84, n_85, n_86, n_87, n_88, n_89, n_90;
  wire n_91, n_92, n_93, n_94, n_95, n_96, n_97, n_98;
  wire n_99, n_100, n_101, n_102, n_103, n_104, n_105, n_106;
  wire n_107, n_108, n_109, n_110, n_111, n_112, n_113, n_114;
  wire n_115, n_116, n_117, n_118, n_119, n_120, n_121, n_122;
  wire n_123, n_124, n_125, n_126, n_127, n_128, n_129, n_130;
  wire n_131, n_132, n_133, n_134, n_135, n_136, n_137, n_138;
  wire n_139, n_140, n_141, n_142, n_143, n_144, n_145, n_146;
  wire n_147, n_148, n_149, n_150, n_151, n_152, n_153, n_154;
  wire n_155, n_156, n_157, n_158, n_159, n_160, n_161, n_162;
  wire n_163, n_164, n_165, n_166, n_167, n_168, n_169, n_170;
  wire n_171, n_172, n_173, n_174, n_175, n_176, n_177, n_178;
  wire n_179, n_180, n_181, n_182, n_183, n_184, n_185, n_186;
  wire n_187, n_188, n_189, n_190, n_191, n_192, n_193, n_194;
  wire n_195, n_196, n_197, n_198, n_199, n_200, n_201, n_202;
  wire n_203, n_204, n_205, n_206, n_207, n_208, n_209, n_210;
  wire n_211, n_212, n_213, n_214, n_215, n_216, n_217, n_218;
  wire n_219, n_220, n_221, n_222, n_223, n_224, n_226, n_227;
  wire n_228, n_229, n_230, scan_out, scan_x;
  DFS3 \circuito_scan_fs_state_reg[0] (.C (CLK), .D (n_228), .SD
       (scan_x), .SE (n_229), .Q (circuito_scan_n_0), .QN
       (circuito_scan_fs_state[0]));
  JKS3 \circuito_scan_fs_state_reg[1] (.C (CLK), .J
       (circuito_scan_n_17), .K (circuito_scan_n_10), .SD
       (circuito_scan_n_0), .SE (n_229), .Q
       (circuito_scan_fs_state[1]), .QN (circuito_scan_n_1));
  DFS3 \circuito_scan_fs_state_reg[2] (.C (CLK), .D
       (circuito_scan_n_19), .SD (circuito_scan_n_1), .SE (n_229), .Q
       (circuito_scan_fs_state[2]), .QN (scan_out));
  CLKIN2 g1823(.A (circuito_scan_n_10), .Q (n_228));
  CLKIN3 g1824(.A (Bist_n_1089), .Q (n_227));
  INV3 g1825(.A (Bist_n_1070), .Q (n_226));
  INV0 g1826(.A (n_230), .Q (out_synced_d));
  INV2 g1827(.A (Bist_n_1064), .Q (n_229));
  INV0 g1830(.A (hf[13]), .Q (n_224));
  INV0 g1828(.A (hf[14]), .Q (n_223));
  INV0 g1831(.A (hf[9]), .Q (n_222));
  CLKIN2 g1834(.A (Bist_count_M[1]), .Q (n_221));
  INV0 g1833(.A (hf[0]), .Q (n_220));
  INV0 g1829(.A (hf[5]), .Q (n_219));
  INV0 g1832(.A (hf[15]), .Q (n_218));
  NAND31 g2630__2398(.A (n_217), .B (n_163), .C
       (circuito_scan_fs_state[2]), .Q (n_230));
  OAI222 g2631__5107(.A (circuito_scan_n_10), .B (n_166), .C (n_211),
       .D (n_186), .Q (circuito_scan_n_19));
  OAI222 g2632__6260(.A (n_214), .B (n_215), .C (n_209), .D
       (circuito_scan_fs_state[0]), .Q (out_sync_err_d));
  INV3 g2633(.A (n_216), .Q (n_217));
  AOI221 g2634__4319(.A (n_215), .B (n_203), .C (n_213), .D
       (circuito_scan_fs_state[1]), .Q (n_216));
  NAND31 g2635__8428(.A (n_215), .B (circuito_scan_fs_state[0]), .C
       (n_164), .Q (circuito_scan_n_10));
  NOR21 g2636__5526(.A (n_212), .B (n_202), .Q (n_215));
  AOI221 g2637__6783(.A (n_210), .B (n_185), .C
       (circuito_scan_fs_state[1]), .D (circuito_scan_fs_state[0]), .Q
       (n_214));
  INV2 g2638(.A (n_212), .Q (n_213));
  IMUX21 g2639__3680(.A (in_x0), .B (in_k), .S (Bist_n_1064), .Q
       (n_212));
  CLKIN3 g2640(.A (circuito_scan_n_17), .Q (n_211));
  NOR21 g2641__1617(.A (RST), .B (n_210), .Q (circuito_scan_n_17));
  DF3 LFSR_in2_x0_reg(.C (CLK), .D (n_206), .Q (scan_x), .QN
       (UNCONNECTED));
  DF3 LFSR_in_x0_reg(.C (CLK), .D (n_205), .Q (in_x0), .QN
       (UNCONNECTED0));
  NAND22 g2644__2802(.A (n_208), .B (n_166), .Q (n_209));
  NAND22 g2645__1705(.A (n_207), .B (n_163), .Q (n_210));
  INV2 g2646(.A (n_207), .Q (n_208));
  NAND22 g2647__5122(.A (n_204), .B (n_164), .Q (n_206));
  NOR21 g2648__8246(.A (n_202), .B (n_203), .Q (n_207));
  OAI212 g2649__7098(.A (Seed), .B (n_165), .C (n_164), .Q (n_205));
  NAND31 g2650__6131(.A (n_201), .B (Bist_n_1071), .C (n_200), .Q
       (bist_end));
  NAND22 g2651__1881(.A (LFSR_in2_x_46), .B (Seed), .Q (n_204));
  IMUX21 g2652__5115(.A (in_x1), .B (in_j), .S (Bist_n_1064), .Q
       (n_203));
  IMUX21 g2653__7482(.A (in_x2), .B (in_en), .S (Bist_n_1064), .Q
       (n_202));
  DLQ3 Bist_Seed_reg(.GN (n_199), .D (n_198), .Q (Seed));
  CLKIN2 g2655(.A (Bist_n_1070), .Q (n_201));
  OAI212 g2656__4733(.A (n_197), .B (Bist_n_1060), .C (Bist_n_1069), .Q
       (Bist_n_1070));
  DLQ3 Comp_passnfail_reg(.GN (n_200), .D (n_194), .Q (pass_fail));
  NAND22 g2658__6161(.A (n_196), .B (Bist_n_1060), .Q (Bist_n_1064));
  NOR40 g2659__9315(.A (n_180), .B (n_193), .C (Bist_n_1084), .D
       (n_195), .Q (n_199));
  NOR40 g2660__9945(.A (n_169), .B (Bist_n_1059), .C (Bist_n_1089), .D
       (n_197), .Q (n_198));
  INV2 g2661(.A (n_197), .Q (n_196));
  NAND22 g2662__2883(.A (Bist_n_1058), .B (n_189), .Q (n_197));
  INV2 g2663(.A (Bist_n_1060), .Q (n_195));
  NOR40 g2664__2346(.A (n_181), .B (n_182), .C (n_191), .D (n_192), .Q
       (n_194));
  NAND41 g2665__1666(.A (n_188), .B (n_173), .C (Bist_count_M[6]), .D
       (Bist_count_M[3]), .Q (Bist_n_1060));
  NAND22 g2666__7410(.A (n_193), .B (Bist_count_N[3]), .Q
       (Bist_n_1058));
  NAND22 g2667__6417(.A (Bist_n_1141), .B (n_200), .Q (Bist_n_1084));
  NOR31 g2668__5477(.A (n_187), .B (n_170), .C (Bist_count_N[1]), .Q
       (n_193));
  CLKIN3 g2669(.A (n_190), .Q (Bist_n_1089));
  NAND40 g2670__2398(.A (n_183), .B (n_171), .C (hf[19]), .D (hf[18]),
       .Q (n_192));
  NAND40 g2671__5107(.A (n_172), .B (n_176), .C (hf[23]), .D (hf[22]),
       .Q (n_191));
  NOR40 g2672__6260(.A (Bist_count_M[5]), .B (Bist_count_M[4]), .C
       (Bist_count_M[6]), .D (Bist_count_M[3]), .Q (n_190));
  INV2 g2673(.A (n_189), .Q (Bist_n_1062));
  NOR21 g2674__4319(.A (Bist_count_M[4]), .B (n_178), .Q (n_188));
  NAND22 g2675__8428(.A (n_179), .B (Bist_state[2]), .Q (Bist_n_1141));
  NOR21 g2676__5526(.A (Bist_state[2]), .B (n_180), .Q (n_189));
  NAND22 g2677__6783(.A (n_175), .B (Bist_state[2]), .Q (Bist_n_1069));
  NAND22 g2678__3680(.A (n_174), .B (Bist_state[2]), .Q (Bist_n_1071));
  INV2 g2679(.A (n_184), .Q (n_187));
  INV2 g2680(.A (n_185), .Q (n_186));
  NOR40 g2681__1617(.A (Bist_count_N[5]), .B (Bist_count_N[6]), .C
       (Bist_count_N[4]), .D (Bist_count_N[2]), .Q (n_184));
  NOR40 g2682__2802(.A (hf[12]), .B (hf[17]), .C (hf[11]), .D (n_223),
       .Q (n_183));
  NAND40 g2683__1705(.A (n_219), .B (hf[4]), .C (hf[3]), .D (hf[2]), .Q
       (n_182));
  NAND40 g2684__5122(.A (n_224), .B (n_222), .C (hf[6]), .D (hf[8]), .Q
       (n_181));
  IMUX21 g2685__8246(.A (n_166), .B (circuito_scan_fs_state[2]), .S
       (circuito_scan_fs_state[1]), .Q (n_185));
  NAND22 g2686__7098(.A (n_177), .B (Bist_state[2]), .Q (n_200));
  INV2 g2687(.A (n_180), .Q (n_179));
  NAND22 g2688__6131(.A (Bist_count_M[5]), .B (Bist_count_M[2]), .Q
       (n_178));
  NOR21 g2689__1881(.A (Bist_state[1]), .B (Bist_state[0]), .Q (n_177));
  NOR20 g2690__5115(.A (hf[20]), .B (hf[21]), .Q (n_176));
  NAND22 g2691__7482(.A (Bist_state[0]), .B (Bist_state[1]), .Q
       (n_180));
  INV2 g2692(.A (n_175), .Q (Bist_n_1129));
  INV2 g2693(.A (n_174), .Q (Bist_n_1132));
  INV2 g2694(.A (n_173), .Q (Bist_n_1059));
  NOR20 g2695__4733(.A (hf[1]), .B (n_220), .Q (n_172));
  NOR20 g2696__6161(.A (hf[16]), .B (n_218), .Q (n_171));
  NOR21 g2697__9315(.A (Bist_state[1]), .B (n_168), .Q (n_175));
  NOR21 g2698__9945(.A (Bist_state[0]), .B (n_167), .Q (n_174));
  NOR21 g2699__2883(.A (Bist_count_M[0]), .B (n_221), .Q (n_173));
  INV3 g2700(.A (Bist_count_N[0]), .Q (n_170));
  INV2 g2701(.A (Bist_count_M[2]), .Q (n_169));
  CLKIN2 g2702(.A (Bist_state[0]), .Q (n_168));
  CLKIN2 g2703(.A (Bist_state[1]), .Q (n_167));
  INV3 g2704(.A (circuito_scan_fs_state[2]), .Q (n_166));
  INV2 g2705(.A (in_x1), .Q (n_165));
  CLKIN3 g2706(.A (RST), .Q (n_164));
  INV3 g2707(.A (circuito_scan_fs_state[0]), .Q (n_163));
  DFC3 \Bist_count_M_reg[0] (.RN (n_19), .C (CLK), .D (n_76), .Q
       (Bist_count_M[0]), .QN (n_9));
  DFC3 \Bist_count_M_reg[1] (.RN (n_19), .C (CLK), .D (n_112), .Q
       (Bist_count_M[1]), .QN (n_14));
  DFC3 \Bist_count_M_reg[2] (.RN (n_19), .C (CLK), .D (n_124), .Q
       (Bist_count_M[2]), .QN (UNCONNECTED1));
  DFC3 \Bist_count_M_reg[3] (.RN (n_19), .C (CLK), .D (n_142), .Q
       (Bist_count_M[3]), .QN (UNCONNECTED2));
  DFC3 \Bist_count_M_reg[4] (.RN (n_19), .C (CLK), .D (n_155), .Q
       (Bist_count_M[4]), .QN (UNCONNECTED3));
  DFC3 \Bist_count_M_reg[5] (.RN (n_19), .C (CLK), .D (n_160), .Q
       (Bist_count_M[5]), .QN (UNCONNECTED4));
  DFC3 \Bist_count_M_reg[6] (.RN (n_19), .C (CLK), .D (n_162), .Q
       (Bist_count_M[6]), .QN (UNCONNECTED5));
  JKC3 \Bist_count_N_reg[0] (.RN (n_19), .C (CLK), .J (n_17), .K
       (n_73), .Q (Bist_count_N[0]), .QN (UNCONNECTED6));
  DFC3 \Bist_count_N_reg[1] (.RN (n_19), .C (CLK), .D (n_100), .Q
       (Bist_count_N[1]), .QN (n_4));
  DFC3 \Bist_count_N_reg[2] (.RN (n_19), .C (CLK), .D (n_130), .Q
       (Bist_count_N[2]), .QN (n_5));
  DFC3 \Bist_count_N_reg[3] (.RN (n_19), .C (CLK), .D (n_139), .Q
       (Bist_count_N[3]), .QN (UNCONNECTED7));
  DFC3 \Bist_count_N_reg[4] (.RN (n_19), .C (CLK), .D (n_149), .Q
       (Bist_count_N[4]), .QN (n_12));
  DFC3 \Bist_count_N_reg[5] (.RN (n_19), .C (CLK), .D (n_152), .Q
       (Bist_count_N[5]), .QN (n_15));
  DFC3 \Bist_count_N_reg[6] (.RN (n_19), .C (CLK), .D (n_151), .Q
       (Bist_count_N[6]), .QN (UNCONNECTED8));
  DFC3 \Bist_state_reg[0] (.RN (n_19), .C (CLK), .D (n_115), .Q
       (Bist_state[0]), .QN (UNCONNECTED9));
  DFC3 \Bist_state_reg[1] (.RN (n_19), .C (CLK), .D (n_113), .Q
       (Bist_state[1]), .QN (UNCONNECTED10));
  DFC3 \Bist_state_reg[2] (.RN (n_19), .C (CLK), .D (n_77), .Q
       (Bist_state[2]), .QN (UNCONNECTED11));
  DF3 LFSR_in2_x1_reg(.C (CLK), .D (n_58), .Q (LFSR_in2_x_46), .QN
       (UNCONNECTED12));
  DF3 LFSR_in2_x2_reg(.C (CLK), .D (n_56), .Q (LFSR_in2_x_47), .QN
       (UNCONNECTED13));
  DF3 LFSR_in2_x3_reg(.C (CLK), .D (n_138), .Q (LFSR_in2_x3), .QN
       (UNCONNECTED14));
  DF3 LFSR_in_x1_reg(.C (CLK), .D (n_55), .Q (in_x1), .QN
       (UNCONNECTED15));
  DF3 LFSR_in_x2_reg(.C (CLK), .D (n_59), .Q (in_x2), .QN (n_6));
  DF3 LFSR_in_x3_reg(.C (CLK), .D (n_141), .Q (LFSR_in_x3), .QN (n_7));
  DF3 MISR_h0_reg(.C (CLK), .D (n_75), .Q (MISR_h0), .QN
       (UNCONNECTED16));
  DF3 MISR_h1_reg(.C (CLK), .D (n_93), .Q (MISR_h1), .QN (n_13));
  DF3 MISR_h2_reg(.C (CLK), .D (n_74), .Q (MISR_h2), .QN (n_2));
  DF3 MISR_h3_reg(.C (CLK), .D (n_101), .Q (MISR_h3), .QN
       (UNCONNECTED17));
  DF3 MISR_h4_reg(.C (CLK), .D (n_110), .Q (MISR_h4), .QN
       (UNCONNECTED18));
  DF3 MISR_h5_reg(.C (CLK), .D (n_87), .Q (MISR_h5), .QN (n_0));
  DF3 MISR_h6_reg(.C (CLK), .D (n_108), .Q (MISR_h6), .QN
       (UNCONNECTED19));
  DF3 MISR_h7_reg(.C (CLK), .D (n_107), .Q (MISR_h7), .QN
       (UNCONNECTED20));
  DF3 MISR_h8_reg(.C (CLK), .D (n_92), .Q (MISR_h8), .QN (n_10));
  DF3 MISR_h9_reg(.C (CLK), .D (n_105), .Q (MISR_h9), .QN
       (UNCONNECTED21));
  DF3 MISR_h10_reg(.C (CLK), .D (n_106), .Q (MISR_h10), .QN
       (UNCONNECTED22));
  DF3 MISR_h11_reg(.C (CLK), .D (n_111), .Q (MISR_h11), .QN
       (UNCONNECTED23));
  DF3 MISR_h12_reg(.C (CLK), .D (n_91), .Q (MISR_h12), .QN (n_11));
  DF3 MISR_h14_reg(.C (CLK), .D (n_104), .Q (MISR_h14), .QN
       (UNCONNECTED24));
  DF3 MISR_h15_reg(.C (CLK), .D (n_95), .Q (MISR_h15), .QN (n_3));
  DF3 MISR_h17_reg(.C (CLK), .D (n_103), .Q (MISR_h17), .QN
       (UNCONNECTED25));
  DF3 MISR_h18_reg(.C (CLK), .D (n_89), .Q (MISR_h18), .QN (n_8));
  DF3 MISR_h19_reg(.C (CLK), .D (n_109), .Q (MISR_h19), .QN
       (UNCONNECTED26));
  DF3 MISR_h20_reg(.C (CLK), .D (n_102), .Q (MISR_h20), .QN
       (UNCONNECTED27));
  DF3 MISR_h21_reg(.C (CLK), .D (n_88), .Q (MISR_h21), .QN (n_1));
  DF3 MISR_h22_reg(.C (CLK), .D (n_97), .Q (MISR_h22), .QN
       (UNCONNECTED28));
  DF3 MISR_h23_reg(.C (CLK), .D (n_154), .Q (MISR_h23), .QN
       (UNCONNECTED29));
  DFE1 \MISR_hf_reg[0] (.C (CLK), .D (MISR_h23), .E (n_27), .Q (hf[0]),
       .QN (UNCONNECTED30));
  DFE1 \MISR_hf_reg[1] (.C (CLK), .D (MISR_h22), .E (n_27), .Q (hf[1]),
       .QN (UNCONNECTED31));
  DFE1 \MISR_hf_reg[2] (.C (CLK), .D (MISR_h21), .E (n_27), .Q (hf[2]),
       .QN (UNCONNECTED32));
  DFE1 \MISR_hf_reg[3] (.C (CLK), .D (MISR_h20), .E (n_27), .Q (hf[3]),
       .QN (UNCONNECTED33));
  DFE1 \MISR_hf_reg[4] (.C (CLK), .D (MISR_h19), .E (n_27), .Q (hf[4]),
       .QN (UNCONNECTED34));
  DFE1 \MISR_hf_reg[5] (.C (CLK), .D (MISR_h18), .E (n_27), .Q (hf[5]),
       .QN (UNCONNECTED35));
  DFE1 \MISR_hf_reg[6] (.C (CLK), .D (MISR_h17), .E (n_27), .Q (hf[6]),
       .QN (UNCONNECTED36));
  DFE1 \MISR_hf_reg[7] (.C (CLK), .D (MISR_h10), .E (n_27), .Q
       (hf[13]), .QN (UNCONNECTED37));
  DFE1 \MISR_hf_reg[8] (.C (CLK), .D (MISR_h15), .E (n_27), .Q (hf[8]),
       .QN (UNCONNECTED38));
  DFE1 \MISR_hf_reg[9] (.C (CLK), .D (MISR_h14), .E (n_27), .Q (hf[9]),
       .QN (UNCONNECTED39));
  DFE1 \MISR_hf_reg[10] (.C (CLK), .D (MISR_h6), .E (n_27), .Q
       (hf[17]), .QN (UNCONNECTED40));
  DFE1 \MISR_hf_reg[11] (.C (CLK), .D (MISR_h12), .E (n_27), .Q
       (hf[11]), .QN (UNCONNECTED41));
  DFE1 \MISR_hf_reg[12] (.C (CLK), .D (MISR_h11), .E (n_27), .Q
       (hf[12]), .QN (UNCONNECTED42));
  DFE1 \MISR_hf_reg[14] (.C (CLK), .D (MISR_h9), .E (n_27), .Q
       (hf[14]), .QN (UNCONNECTED43));
  DFE1 \MISR_hf_reg[15] (.C (CLK), .D (MISR_h8), .E (n_27), .Q
       (hf[15]), .QN (UNCONNECTED44));
  DFE1 \MISR_hf_reg[16] (.C (CLK), .D (MISR_h7), .E (n_27), .Q
       (hf[16]), .QN (UNCONNECTED45));
  DFE1 \MISR_hf_reg[18] (.C (CLK), .D (MISR_h5), .E (n_27), .Q
       (hf[18]), .QN (UNCONNECTED46));
  DFE1 \MISR_hf_reg[19] (.C (CLK), .D (MISR_h4), .E (n_27), .Q
       (hf[19]), .QN (UNCONNECTED47));
  DFE1 \MISR_hf_reg[20] (.C (CLK), .D (MISR_h3), .E (n_27), .Q
       (hf[20]), .QN (UNCONNECTED48));
  DFE1 \MISR_hf_reg[21] (.C (CLK), .D (MISR_h2), .E (n_27), .Q
       (hf[21]), .QN (UNCONNECTED49));
  DFE1 \MISR_hf_reg[22] (.C (CLK), .D (MISR_h1), .E (n_27), .Q
       (hf[22]), .QN (UNCONNECTED50));
  DFE1 \MISR_hf_reg[23] (.C (CLK), .D (MISR_h0), .E (n_27), .Q
       (hf[23]), .QN (UNCONNECTED51));
  NOR21 g3604__2346(.A (n_20), .B (n_161), .Q (n_162));
  IMUX21 g3606__1666(.A (n_158), .B (Bist_count_M[6]), .S
       (Bist_n_1058), .Q (n_161));
  NOR21 g3607__7410(.A (n_20), .B (n_159), .Q (n_160));
  IMUX21 g3608__6417(.A (n_157), .B (Bist_count_M[5]), .S
       (Bist_n_1058), .Q (n_159));
  XOR21 g3609__5477(.A (Bist_count_M[6]), .B (n_156), .Q (n_158));
  ADD22 g3612__2398(.A (n_143), .B (Bist_count_M[5]), .CO (n_156), .S
       (n_157));
  NOR21 g3615__5107(.A (n_20), .B (n_150), .Q (n_155));
  NAND22 g3616__6260(.A (n_153), .B (n_19), .Q (n_154));
  AOI221 g3617__4319(.A (n_137), .B (n_29), .C (MISR_h23), .D (n_26),
       .Q (n_153));
  OAI311 g3619__8428(.A (Bist_count_N[5]), .B (n_132), .C
       (Bist_n_1064), .D (n_147), .Q (n_152));
  OAI212 g3620__5526(.A (Bist_n_1064), .B (n_140), .C (n_148), .Q
       (n_151));
  IMUX21 g3621__6783(.A (n_144), .B (Bist_count_M[4]), .S
       (Bist_n_1058), .Q (n_150));
  INV3 g3625(.A (n_146), .Q (n_149));
  NAND22 g3626__3680(.A (n_145), .B (Bist_count_N[6]), .Q (n_148));
  NAND22 g3627__1617(.A (n_145), .B (Bist_count_N[5]), .Q (n_147));
  AOI221 g3628__2802(.A (n_17), .B (n_134), .C (n_133), .D
       (Bist_count_N[4]), .Q (n_146));
  ADD22 g3630__1705(.A (n_125), .B (Bist_count_M[4]), .CO (n_143), .S
       (n_144));
  NOR21 g3631__5122(.A (n_20), .B (n_135), .Q (n_142));
  NAND31 g3632__8246(.A (n_128), .B (n_21), .C (n_19), .Q (n_141));
  OAI211 g3633__7098(.A (n_131), .B (Bist_n_1064), .C (n_73), .Q
       (n_145));
  AOI221 g3634__6131(.A (n_131), .B (n_30), .C (n_15), .D
       (Bist_count_N[6]), .Q (n_140));
  OAI311 g3635__1881(.A (Bist_count_N[3]), .B (n_121), .C
       (Bist_n_1064), .D (n_136), .Q (n_139));
  NAND31 g3636__5115(.A (n_129), .B (Seed), .C (n_19), .Q (n_138));
  XNR41 g3637__7482(.A (n_84), .B (n_83), .C (n_82), .D (n_117), .Q
       (n_137));
  NAND22 g3638__4733(.A (n_133), .B (Bist_count_N[3]), .Q (n_136));
  IMUX21 g3640__6161(.A (n_126), .B (Bist_count_M[3]), .S
       (Bist_n_1058), .Q (n_135));
  IMUX21 g3641__9315(.A (n_127), .B (Bist_count_N[3]), .S
       (Bist_count_N[4]), .Q (n_134));
  INV2 g3642(.A (n_131), .Q (n_132));
  OAI212 g3643__9945(.A (n_122), .B (Bist_n_1064), .C (n_73), .Q
       (n_133));
  NOR21 g3644__2883(.A (n_12), .B (n_127), .Q (n_131));
  OAI222 g3646__2346(.A (Bist_n_1064), .B (n_123), .C (n_73), .D (n_5),
       .Q (n_130));
  XNR21 g3647__1666(.A (LFSR_in2_x_47), .B (n_116), .Q (n_129));
  XNR21 g3648__7410(.A (in_x2), .B (n_118), .Q (n_128));
  ADD22 g3649__6417(.A (n_98), .B (Bist_count_M[3]), .CO (n_125), .S
       (n_126));
  NAND22 g3650__5477(.A (n_122), .B (Bist_count_N[3]), .Q (n_127));
  NOR21 g3651__2398(.A (n_20), .B (n_119), .Q (n_124));
  INV2 g3652(.A (n_120), .Q (n_123));
  INV2 g3653(.A (n_122), .Q (n_121));
  ADD22 g3654__5107(.A (n_79), .B (Bist_count_N[2]), .CO (n_122), .S
       (n_120));
  IMUX20 g3664__6260(.A (n_99), .B (Bist_count_M[2]), .S (Bist_n_1058),
       .Q (n_119));
  MUX22 g3665__4319(.A (LFSR_in_x3), .B (in_x1), .S (n_96), .Q (n_118));
  XOR41 g3666__8428(.A (n_46), .B (n_51), .C (n_52), .D (n_47), .Q
       (n_117));
  MUX22 g3667__5526(.A (LFSR_in2_x3), .B (LFSR_in2_x_46), .S (n_96), .Q
       (n_116));
  CLKIN2 g3674(.A (n_114), .Q (n_115));
  NOR40 g3675__6783(.A (n_60), .B (n_25), .C (Bist_n_1084), .D (n_78),
       .Q (n_114));
  NAND22 g3676__3680(.A (Bist_n_1071), .B (n_90), .Q (n_113));
  NOR21 g3677__1617(.A (n_20), .B (n_85), .Q (n_112));
  OAI2111 g3687__2802(.A (n_28), .B (n_35), .C (n_63), .D (n_19), .Q
       (n_111));
  OAI2111 g3688__1705(.A (n_28), .B (n_37), .C (n_65), .D (n_19), .Q
       (n_110));
  OAI2111 g3689__5122(.A (n_28), .B (n_39), .C (n_70), .D (n_19), .Q
       (n_109));
  OAI2111 g3690__8246(.A (n_28), .B (n_50), .C (n_64), .D (n_19), .Q
       (n_108));
  OAI2111 g3691__7098(.A (n_28), .B (n_52), .C (n_67), .D (n_19), .Q
       (n_107));
  OAI2111 g3692__6131(.A (n_28), .B (n_49), .C (n_66), .D (n_19), .Q
       (n_106));
  NAND22 g3693__1881(.A (n_86), .B (n_19), .Q (n_105));
  OAI2111 g3694__5115(.A (n_28), .B (n_51), .C (n_71), .D (n_19), .Q
       (n_104));
  OAI2111 g3695__7482(.A (n_28), .B (n_41), .C (n_68), .D (n_19), .Q
       (n_103));
  OAI2111 g3696__4733(.A (n_28), .B (n_47), .C (n_72), .D (n_19), .Q
       (n_102));
  OAI2111 g3697__6161(.A (n_28), .B (n_36), .C (n_69), .D (n_19), .Q
       (n_101));
  OAI222 g3698__9315(.A (Bist_n_1064), .B (n_81), .C (n_73), .D (n_4),
       .Q (n_100));
  ADD22 g3699__9945(.A (n_23), .B (Bist_count_M[2]), .CO (n_98), .S
       (n_99));
  CLKIN2 g3720(.A (n_94), .Q (n_97));
  OAI221 g3721__2883(.A (n_53), .B (n_28), .C (n_3), .D (n_27), .Q
       (n_95));
  AOI221 g3722__2346(.A (n_45), .B (n_29), .C (MISR_h22), .D (n_26), .Q
       (n_94));
  OAI221 g3723__1666(.A (n_48), .B (n_28), .C (n_13), .D (n_27), .Q
       (n_93));
  OAI221 g3724__7410(.A (n_34), .B (n_28), .C (n_10), .D (n_27), .Q
       (n_92));
  OAI221 g3725__6417(.A (n_40), .B (n_28), .C (n_11), .D (n_27), .Q
       (n_91));
  AOI2111 g3726__5477(.A (n_32), .B (bist_start), .C (n_62), .D (n_78),
       .Q (n_90));
  OAI221 g3727__2398(.A (n_46), .B (n_28), .C (n_8), .D (n_27), .Q
       (n_89));
  OAI222 g3728__5107(.A (n_38), .B (n_28), .C (n_1), .D (n_27), .Q
       (n_88));
  OAI221 g3729__6260(.A (n_42), .B (n_28), .C (n_0), .D (n_27), .Q
       (n_87));
  IMUX21 g3730__4319(.A (n_54), .B (MISR_h9), .S (bist_end), .Q (n_86));
  IMUX20 g3731__8428(.A (n_61), .B (Bist_count_M[1]), .S (Bist_n_1058),
       .Q (n_85));
  XNR41 g3734__5526(.A (MISR_h18), .B (MISR_h22), .C (MISR_h5), .D
       (MISR_h20), .Q (n_84));
  XNR21 g3739__6783(.A (n_50), .B (n_49), .Q (n_83));
  XOR31 g3740__3680(.A (scan_out), .B (MISR_h4), .C (n_48), .Q (n_82));
  AOI211 g3741__1617(.A (n_227), .B (n_57), .C (Bist_n_1064), .Q
       (n_96));
  INV2 g3742(.A (n_80), .Q (n_81));
  ADD22 g3743__2802(.A (Bist_count_N[1]), .B (Bist_count_N[0]), .CO
       (n_79), .S (n_80));
  OAI2111 g3748__1705(.A (bist_start), .B (Bist_n_1071), .C (n_226), .D
       (n_22), .Q (n_77));
  NOR21 g3749__5122(.A (n_20), .B (n_44), .Q (n_76));
  NAND22 g3750__8246(.A (n_43), .B (n_19), .Q (n_75));
  OAI211 g3751__7098(.A (n_27), .B (n_2), .C (n_19), .Q (n_74));
  OAI222 g3752__6131(.A (n_24), .B (Bist_n_1062), .C (Bist_n_1132), .D
       (Bist_state[2]), .Q (n_78));
  NAND21 g3753__1881(.A (MISR_h20), .B (n_26), .Q (n_72));
  NAND21 g3754__5115(.A (MISR_h14), .B (n_26), .Q (n_71));
  NAND21 g3755__7482(.A (MISR_h19), .B (n_26), .Q (n_70));
  NAND21 g3756__4733(.A (MISR_h3), .B (n_26), .Q (n_69));
  NAND21 g3757__6161(.A (MISR_h17), .B (n_26), .Q (n_68));
  NAND21 g3758__9315(.A (MISR_h7), .B (n_26), .Q (n_67));
  NAND21 g3759__9945(.A (MISR_h10), .B (n_26), .Q (n_66));
  NAND21 g3760__2883(.A (MISR_h4), .B (n_26), .Q (n_65));
  NAND21 g3761__2346(.A (MISR_h6), .B (n_26), .Q (n_64));
  NAND21 g3762__1666(.A (MISR_h11), .B (n_26), .Q (n_63));
  OAI212 g3763__7410(.A (bist_start), .B (Bist_n_1069), .C
       (Bist_n_1141), .Q (n_62));
  OAI211 g3764__6417(.A (Bist_count_M[1]), .B (n_9), .C (Bist_n_1059),
       .Q (n_61));
  NOR31 g3765__5477(.A (Bist_state[1]), .B (Bist_state[2]), .C
       (bist_start), .Q (n_60));
  OAI212 g3766__2398(.A (Seed), .B (n_7), .C (n_19), .Q (n_59));
  NAND22 g3767__5107(.A (n_31), .B (n_19), .Q (n_58));
  OAI212 g3768__6260(.A (Bist_count_M[0]), .B (Bist_count_M[1]), .C
       (Bist_count_M[2]), .Q (n_57));
  NAND22 g3769__4319(.A (n_33), .B (n_19), .Q (n_56));
  OAI212 g3770__8428(.A (Seed), .B (n_6), .C (n_19), .Q (n_55));
  NAND31 g3771__5526(.A (Bist_n_1060), .B (Bist_n_1058), .C
       (Bist_n_1062), .Q (n_73));
  INV2 g3772(.A (n_53), .Q (n_54));
  IMUX20 g3773__6783(.A (MISR_h21), .B (n_1), .S (n_230), .Q (n_45));
  IMUX20 g3774__3680(.A (n_9), .B (Bist_count_M[0]), .S (Bist_n_1058),
       .Q (n_44));
  IMUX21 g3775__1617(.A (MISR_h1), .B (MISR_h0), .S (bist_end), .Q
       (n_43));
  IMUX20 g3776__2802(.A (MISR_h2), .B (n_2), .S (MISR_h6), .Q (n_42));
  IMUX20 g3777__1705(.A (MISR_h15), .B (n_3), .S (MISR_h18), .Q (n_41));
  IMUX20 g3778__5122(.A (MISR_h5), .B (n_0), .S (MISR_h6), .Q (n_40));
  XNR21 g3779__8246(.A (MISR_h20), .B (MISR_h17), .Q (n_39));
  XNR21 g3780__7098(.A (out_sync_err_d), .B (MISR_h20), .Q (n_38));
  IMUX20 g3781__6131(.A (MISR_h5), .B (n_0), .S (MISR_h7), .Q (n_37));
  XNR21 g3782__1881(.A (MISR_h4), .B (MISR_h0), .Q (n_36));
  IMUX20 g3783__5115(.A (MISR_h8), .B (n_10), .S (MISR_h12), .Q (n_35));
  XNR21 g3784__7482(.A (MISR_h10), .B (MISR_h9), .Q (n_34));
  XNR21 g3785__4733(.A (MISR_h10), .B (MISR_h6), .Q (n_53));
  IMUX21 g3786__6161(.A (MISR_h8), .B (n_10), .S (MISR_h3), .Q (n_52));
  IMUX21 g3787__9315(.A (MISR_h15), .B (n_3), .S (MISR_h9), .Q (n_51));
  XNR21 g3788__9945(.A (MISR_h14), .B (MISR_h7), .Q (n_50));
  XNR21 g3789__2883(.A (MISR_h17), .B (MISR_h11), .Q (n_49));
  IMUX21 g3790__2346(.A (MISR_h1), .B (n_13), .S (MISR_h2), .Q (n_48));
  IMUX21 g3791__1666(.A (MISR_h21), .B (n_1), .S (MISR_h0), .Q (n_47));
  IMUX21 g3792__7410(.A (MISR_h12), .B (n_11), .S (MISR_h19), .Q
       (n_46));
  NAND22 g3793__6417(.A (LFSR_in2_x3), .B (Seed), .Q (n_33));
  NOR21 g3794__5477(.A (Bist_state[2]), .B (Bist_n_1129), .Q (n_32));
  NAND22 g3795__2398(.A (LFSR_in2_x_47), .B (Seed), .Q (n_31));
  NOR21 g3796__5107(.A (Bist_count_N[6]), .B (n_15), .Q (n_30));
  INV3 g3797(.A (n_29), .Q (n_28));
  INV3 g3798(.A (n_27), .Q (n_26));
  NOR21 g3799__6260(.A (n_18), .B (Bist_n_1069), .Q (n_25));
  NOR21 g3800__4319(.A (n_16), .B (Bist_n_1060), .Q (n_24));
  NOR21 g3801__8428(.A (n_14), .B (n_9), .Q (n_23));
  NOR21 g3802__5526(.A (RST), .B (bist_end), .Q (n_29));
  NAND22 g3803__6783(.A (bist_end), .B (n_19), .Q (n_27));
  INV2 g3804(.A (Bist_n_1084), .Q (n_22));
  INV2 g3822(.A (Seed), .Q (n_21));
  INV3 g3828(.A (Bist_n_1060), .Q (n_20));
  INV3 g3829(.A (RST), .Q (n_19));
  INV2 g3843(.A (bist_start), .Q (n_18));
  INV2 g3850(.A (Bist_n_1064), .Q (n_17));
  INV2 g3851(.A (Bist_n_1058), .Q (n_16));
endmodule

