`timescale 1ns/1ps 
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Jan  7 2024 15:45:04 WET (Jan  7 2024 15:45:04 UTC)

// Verification Directory fv/main 

module main(CLK, RST, bist_start, bist_end, pass_fail, in_k, in_j,
     in_en, out_synced_d, out_sync_err_d);
  input CLK, RST, bist_start, in_k, in_j, in_en;
  output bist_end, pass_fail, out_synced_d, out_sync_err_d;
  wire CLK, RST, bist_start, in_k, in_j, in_en;
  wire bist_end, pass_fail, out_synced_d, out_sync_err_d;
  wire [2:0] circuito_scan_fs_state;
  wire [6:0] Bist_count_N;
  wire [20:0] hf;
  wire [6:0] Bist_count_M;
  wire [2:0] Bist_state;
  wire LFSR_in2_x_30, LFSR_in2_x_31, MISR_h0, MISR_h1, MISR_h2,
       MISR_h3, MISR_h4, MISR_h5;
  wire MISR_h6, MISR_h7, MISR_h8, MISR_h9, MISR_h10, MISR_h11,
       MISR_h12, MISR_h13;
  wire MISR_h14, MISR_h15, MISR_h16, MISR_h17, MISR_h18, MISR_h19,
       MISR_h20, UNCONNECTED;
  wire UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, UNCONNECTED3,
       UNCONNECTED4, UNCONNECTED5, UNCONNECTED6, UNCONNECTED7;
  wire UNCONNECTED8, UNCONNECTED9, UNCONNECTED10, UNCONNECTED11,
       UNCONNECTED12, UNCONNECTED13, UNCONNECTED14, UNCONNECTED15;
  wire UNCONNECTED16, UNCONNECTED17, UNCONNECTED18, UNCONNECTED19,
       UNCONNECTED20, UNCONNECTED21, UNCONNECTED22, UNCONNECTED23;
  wire UNCONNECTED24, UNCONNECTED25, UNCONNECTED26, UNCONNECTED27,
       UNCONNECTED28, UNCONNECTED29, UNCONNECTED30, UNCONNECTED31;
  wire UNCONNECTED32, UNCONNECTED33, UNCONNECTED34, UNCONNECTED35,
       UNCONNECTED36, UNCONNECTED37, UNCONNECTED38, UNCONNECTED39;
  wire UNCONNECTED40, UNCONNECTED41, UNCONNECTED42, UNCONNECTED43,
       UNCONNECTED44, UNCONNECTED45, UNCONNECTED46, UNCONNECTED47;
  wire UNCONNECTED48, UNCONNECTED49, UNCONNECTED50, circuito_scan_n_0,
       circuito_scan_n_1, circuito_scan_n_10, circuito_scan_n_17,
       circuito_scan_n_19;
  wire in_x0, in_x1, in_x2, n_0, n_1, n_2, n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_100;
  wire n_101, n_102, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_115, n_116;
  wire n_117, n_118, n_119, n_120, n_121, n_122, n_123, n_124;
  wire n_125, n_126, n_127, n_128, n_129, n_130, n_131, n_132;
  wire n_133, n_134, n_135, n_136, n_137, n_138, n_139, n_140;
  wire n_141, n_142, n_143, n_144, n_145, n_146, n_147, n_148;
  wire n_149, n_150, n_151, n_152, n_153, n_154, n_155, n_156;
  wire n_157, n_158, n_159, n_160, n_161, n_162, n_163, n_164;
  wire n_165, n_166, n_167, n_168, n_169, n_170, n_171, n_172;
  wire n_173, n_174, n_175, n_176, n_177, n_178, n_179, n_180;
  wire n_181, n_182, n_183, n_184, n_185, n_186, n_187, n_189;
  wire n_190, n_191, n_192, n_193, n_194, n_195, n_196, n_197;
  wire n_198, n_199, n_200, n_201, n_202, n_203, n_204, n_205;
  wire n_206, n_207, scan_out, scan_x;
  DFS3 \circuito_scan_fs_state_reg[0] (.C (CLK), .D (n_190), .SD
       (scan_x), .SE (n_191), .Q (circuito_scan_n_0), .QN
       (circuito_scan_fs_state[0]));
  JKS3 \circuito_scan_fs_state_reg[1] (.C (CLK), .J
       (circuito_scan_n_17), .K (circuito_scan_n_10), .SD
       (circuito_scan_n_0), .SE (n_191), .Q
       (circuito_scan_fs_state[1]), .QN (circuito_scan_n_1));
  DFS3 \circuito_scan_fs_state_reg[2] (.C (CLK), .D
       (circuito_scan_n_19), .SD (circuito_scan_n_1), .SE (n_191), .Q
       (circuito_scan_fs_state[2]), .QN (scan_out));
  CLKIN2 g2302(.A (circuito_scan_n_10), .Q (n_190));
  INV2 g2303(.A (n_203), .Q (n_191));
  INV2 g2304(.A (n_196), .Q (n_189));
  INV0 g2305(.A (n_199), .Q (out_synced_d));
  CLKIN2 g2307(.A (Bist_count_N[3]), .Q (n_187));
  INV0 g2310(.A (hf[6]), .Q (n_186));
  INV0 g2306(.A (hf[3]), .Q (n_185));
  INV0 g2308(.A (hf[20]), .Q (n_184));
  INV0 g2309(.A (hf[16]), .Q (n_183));
  OAI222 g3124__2398(.A (n_182), .B (n_176), .C (n_178), .D
       (circuito_scan_fs_state[0]), .Q (out_sync_err_d));
  NAND31 g3125__5107(.A (n_180), .B (n_145), .C
       (circuito_scan_fs_state[2]), .Q (n_199));
  OAI222 g3126__6260(.A (n_181), .B (n_159), .C (circuito_scan_n_10),
       .D (n_144), .Q (circuito_scan_n_19));
  AOI221 g3127__4319(.A (n_177), .B (n_158), .C
       (circuito_scan_fs_state[1]), .D (circuito_scan_fs_state[0]), .Q
       (n_182));
  INV2 g3128(.A (circuito_scan_n_17), .Q (n_181));
  NOR21 g3129__8428(.A (RST), .B (n_177), .Q (circuito_scan_n_17));
  INV3 g3130(.A (n_179), .Q (n_180));
  AOI221 g3131__5526(.A (n_176), .B (n_170), .C (n_173), .D
       (circuito_scan_fs_state[1]), .Q (n_179));
  NAND31 g3132__6783(.A (n_176), .B (circuito_scan_fs_state[0]), .C
       (n_147), .Q (circuito_scan_n_10));
  NAND22 g3133__3680(.A (n_175), .B (n_144), .Q (n_178));
  NAND22 g3134__1617(.A (n_174), .B (n_145), .Q (n_177));
  NOR21 g3135__2802(.A (n_172), .B (n_171), .Q (n_176));
  INV2 g3136(.A (n_174), .Q (n_175));
  NOR21 g3137__1705(.A (n_171), .B (n_170), .Q (n_174));
  INV2 g3138(.A (n_172), .Q (n_173));
  NAND31 g3139__5122(.A (n_169), .B (n_200), .C (n_201), .Q (bist_end));
  IMUX21 g3140__8246(.A (in_x0), .B (in_k), .S (n_203), .Q (n_172));
  IMUX21 g3141__7098(.A (in_x2), .B (in_en), .S (n_203), .Q (n_171));
  IMUX21 g3142__6131(.A (in_x1), .B (in_j), .S (n_203), .Q (n_170));
  INV3 g3143(.A (n_202), .Q (n_169));
  OAI212 g3144__1881(.A (n_206), .B (n_196), .C (n_207), .Q (n_202));
  DLQ3 Comp_passnfail_reg(.GN (n_207), .D (n_167), .Q (pass_fail));
  NAND22 g3146__5115(.A (n_168), .B (n_162), .Q (n_203));
  NAND22 g3147__7482(.A (n_166), .B (n_205), .Q (n_196));
  INV2 g3148(.A (n_192), .Q (n_168));
  NOR40 g3149__4733(.A (n_160), .B (n_154), .C (n_163), .D (n_164), .Q
       (n_167));
  NAND22 g3150__6161(.A (n_204), .B (n_205), .Q (n_192));
  INV2 g3151(.A (n_166), .Q (n_204));
  NOR21 g3152__9315(.A (n_197), .B (n_165), .Q (n_166));
  NAND41 g3153__9945(.A (n_151), .B (Bist_count_M[5]), .C
       (Bist_count_M[6]), .D (Bist_count_M[2]), .Q (n_165));
  NAND33 g3154__2883(.A (n_156), .B (n_153), .C (Bist_count_N[0]), .Q
       (n_205));
  NAND40 g3155__2346(.A (n_155), .B (n_148), .C (hf[18]), .D (hf[12]),
       .Q (n_164));
  NAND30 g3156__1666(.A (n_161), .B (hf[0]), .C (hf[2]), .Q (n_163));
  INV3 g3157(.A (n_162), .Q (n_206));
  NOR30 g3158__7410(.A (n_184), .B (hf[1]), .C (hf[11]), .Q (n_161));
  NAND22 g3159__6417(.A (n_150), .B (Bist_state[2]), .Q (n_200));
  NAND22 g3160__5477(.A (n_149), .B (Bist_state[2]), .Q (n_201));
  NAND31 g3161__2398(.A (n_143), .B (Bist_state[2]), .C (n_146), .Q
       (n_207));
  NOR21 g3162__5107(.A (Bist_state[2]), .B (n_194), .Q (n_162));
  INV2 g3163(.A (n_157), .Q (n_160));
  INV2 g3164(.A (n_158), .Q (n_159));
  NOR40 g3165__6260(.A (hf[10]), .B (hf[9]), .C (hf[8]), .D (hf[7]), .Q
       (n_157));
  NOR40 g3166__4319(.A (Bist_count_N[4]), .B (Bist_count_N[2]), .C
       (Bist_count_N[1]), .D (n_187), .Q (n_156));
  NOR40 g3167__8428(.A (hf[15]), .B (hf[14]), .C (hf[13]), .D (n_183),
       .Q (n_155));
  NAND40 g3168__5526(.A (n_185), .B (n_186), .C (hf[4]), .D (hf[5]), .Q
       (n_154));
  IMUX21 g3169__6783(.A (n_144), .B (circuito_scan_fs_state[2]), .S
       (circuito_scan_fs_state[1]), .Q (n_158));
  INV3 g3170(.A (n_152), .Q (n_197));
  NOR21 g3171__3680(.A (Bist_count_N[6]), .B (Bist_count_N[5]), .Q
       (n_153));
  NAND22 g3172__1617(.A (Bist_state[0]), .B (Bist_state[1]), .Q
       (n_194));
  NOR21 g3173__2802(.A (Bist_count_M[3]), .B (Bist_count_M[4]), .Q
       (n_152));
  INV2 g3174(.A (n_151), .Q (n_198));
  INV2 g3175(.A (n_150), .Q (n_193));
  INV2 g3176(.A (n_149), .Q (n_195));
  NOR20 g3177__1705(.A (hf[19]), .B (hf[17]), .Q (n_148));
  NOR21 g3178__5122(.A (Bist_count_M[0]), .B (Bist_count_M[1]), .Q
       (n_151));
  NOR21 g3179__8246(.A (Bist_state[1]), .B (n_143), .Q (n_150));
  NOR21 g3180__7098(.A (n_146), .B (Bist_state[0]), .Q (n_149));
  INV2 g3181(.A (RST), .Q (n_147));
  INV2 g3182(.A (Bist_state[1]), .Q (n_146));
  INV3 g3183(.A (circuito_scan_fs_state[0]), .Q (n_145));
  INV3 g3184(.A (circuito_scan_fs_state[2]), .Q (n_144));
  INV2 g3185(.A (Bist_state[0]), .Q (n_143));
  DFC3 \Bist_count_M_reg[0] (.RN (n_15), .C (CLK), .D (n_85), .Q
       (Bist_count_M[0]), .QN (UNCONNECTED));
  DFC3 \Bist_count_M_reg[1] (.RN (n_15), .C (CLK), .D (n_113), .Q
       (Bist_count_M[1]), .QN (UNCONNECTED0));
  DFC3 \Bist_count_M_reg[2] (.RN (n_15), .C (CLK), .D (n_125), .Q
       (Bist_count_M[2]), .QN (UNCONNECTED1));
  DFC3 \Bist_count_M_reg[3] (.RN (n_15), .C (CLK), .D (n_131), .Q
       (Bist_count_M[3]), .QN (UNCONNECTED2));
  DFC3 \Bist_count_M_reg[4] (.RN (n_15), .C (CLK), .D (n_135), .Q
       (Bist_count_M[4]), .QN (UNCONNECTED3));
  DFC3 \Bist_count_M_reg[5] (.RN (n_15), .C (CLK), .D (n_140), .Q
       (Bist_count_M[5]), .QN (n_3));
  DFC3 \Bist_count_M_reg[6] (.RN (n_15), .C (CLK), .D (n_142), .Q
       (Bist_count_M[6]), .QN (UNCONNECTED4));
  DFSC3 \Bist_count_N_reg[0] (.RN (n_15), .C (CLK), .D (n_18), .SD
       (n_29), .SE (Bist_count_N[0]), .Q (Bist_count_N[0]), .QN
       (UNCONNECTED5));
  DFC3 \Bist_count_N_reg[1] (.RN (n_15), .C (CLK), .D (n_91), .Q
       (Bist_count_N[1]), .QN (n_2));
  DFC3 \Bist_count_N_reg[2] (.RN (n_15), .C (CLK), .D (n_99), .Q
       (Bist_count_N[2]), .QN (n_4));
  DFC3 \Bist_count_N_reg[3] (.RN (n_15), .C (CLK), .D (n_109), .Q
       (Bist_count_N[3]), .QN (n_13));
  DFC3 \Bist_count_N_reg[4] (.RN (n_15), .C (CLK), .D (n_117), .Q
       (Bist_count_N[4]), .QN (n_11));
  DFC3 \Bist_count_N_reg[5] (.RN (n_15), .C (CLK), .D (n_122), .Q
       (Bist_count_N[5]), .QN (n_6));
  DFC3 \Bist_count_N_reg[6] (.RN (n_15), .C (CLK), .D (n_121), .Q
       (Bist_count_N[6]), .QN (n_7));
  DFC3 \Bist_state_reg[0] (.RN (n_15), .C (CLK), .D (n_112), .Q
       (Bist_state[0]), .QN (UNCONNECTED6));
  DFC3 \Bist_state_reg[1] (.RN (n_15), .C (CLK), .D (n_107), .Q
       (Bist_state[1]), .QN (UNCONNECTED7));
  DFC3 \Bist_state_reg[2] (.RN (n_15), .C (CLK), .D (n_94), .Q
       (Bist_state[2]), .QN (n_5));
  DF3 LFSR_in2_x0_reg(.C (CLK), .D (n_36), .Q (scan_x), .QN
       (UNCONNECTED8));
  DF3 LFSR_in2_x1_reg(.C (CLK), .D (n_35), .Q (LFSR_in2_x_30), .QN
       (n_10));
  DF3 LFSR_in2_x2_reg(.C (CLK), .D (n_129), .Q (LFSR_in2_x_31), .QN
       (n_14));
  DF3 LFSR_in_x0_reg(.C (CLK), .D (n_33), .Q (in_x0), .QN
       (UNCONNECTED9));
  DF3 LFSR_in_x1_reg(.C (CLK), .D (n_32), .Q (in_x1), .QN (n_8));
  DF3 LFSR_in_x2_reg(.C (CLK), .D (n_128), .Q (in_x2), .QN (n_9));
  DF3 MISR_h0_reg(.C (CLK), .D (n_65), .Q (MISR_h0), .QN
       (UNCONNECTED10));
  DF3 MISR_h1_reg(.C (CLK), .D (n_72), .Q (MISR_h1), .QN
       (UNCONNECTED11));
  DF3 MISR_h2_reg(.C (CLK), .D (n_70), .Q (MISR_h2), .QN
       (UNCONNECTED12));
  DF3 MISR_h3_reg(.C (CLK), .D (n_69), .Q (MISR_h3), .QN
       (UNCONNECTED13));
  DF3 MISR_h4_reg(.C (CLK), .D (n_68), .Q (MISR_h4), .QN
       (UNCONNECTED14));
  DF3 MISR_h5_reg(.C (CLK), .D (n_76), .Q (MISR_h5), .QN
       (UNCONNECTED15));
  DF3 MISR_h6_reg(.C (CLK), .D (n_84), .Q (MISR_h6), .QN
       (UNCONNECTED16));
  DF3 MISR_h7_reg(.C (CLK), .D (n_83), .Q (MISR_h7), .QN
       (UNCONNECTED17));
  DF3 MISR_h8_reg(.C (CLK), .D (n_75), .Q (MISR_h8), .QN
       (UNCONNECTED18));
  DF3 MISR_h9_reg(.C (CLK), .D (n_82), .Q (MISR_h9), .QN
       (UNCONNECTED19));
  DF3 MISR_h10_reg(.C (CLK), .D (n_86), .Q (MISR_h10), .QN
       (UNCONNECTED20));
  DF3 MISR_h11_reg(.C (CLK), .D (n_80), .Q (MISR_h11), .QN
       (UNCONNECTED21));
  DF3 MISR_h12_reg(.C (CLK), .D (n_74), .Q (MISR_h12), .QN
       (UNCONNECTED22));
  DF3 MISR_h13_reg(.C (CLK), .D (n_79), .Q (MISR_h13), .QN
       (UNCONNECTED23));
  DF3 MISR_h14_reg(.C (CLK), .D (n_78), .Q (MISR_h14), .QN
       (UNCONNECTED24));
  DF3 MISR_h15_reg(.C (CLK), .D (n_73), .Q (MISR_h15), .QN
       (UNCONNECTED25));
  DF3 MISR_h16_reg(.C (CLK), .D (n_77), .Q (MISR_h16), .QN
       (UNCONNECTED26));
  DF3 MISR_h17_reg(.C (CLK), .D (n_81), .Q (MISR_h17), .QN
       (UNCONNECTED27));
  DF3 MISR_h18_reg(.C (CLK), .D (n_92), .Q (MISR_h18), .QN (n_12));
  DF3 MISR_h19_reg(.C (CLK), .D (n_105), .Q (MISR_h19), .QN
       (UNCONNECTED28));
  DF3 MISR_h20_reg(.C (CLK), .D (n_100), .Q (MISR_h20), .QN
       (UNCONNECTED29));
  DFE1 \MISR_hf_reg[0] (.C (CLK), .D (MISR_h20), .E (n_26), .Q (hf[0]),
       .QN (UNCONNECTED30));
  DFE1 \MISR_hf_reg[1] (.C (CLK), .D (MISR_h19), .E (n_26), .Q (hf[1]),
       .QN (UNCONNECTED31));
  DFE1 \MISR_hf_reg[2] (.C (CLK), .D (MISR_h18), .E (n_26), .Q (hf[2]),
       .QN (UNCONNECTED32));
  DFE1 \MISR_hf_reg[3] (.C (CLK), .D (MISR_h17), .E (n_26), .Q (hf[3]),
       .QN (UNCONNECTED33));
  DFE1 \MISR_hf_reg[4] (.C (CLK), .D (MISR_h16), .E (n_26), .Q (hf[4]),
       .QN (UNCONNECTED34));
  DFE1 \MISR_hf_reg[5] (.C (CLK), .D (MISR_h15), .E (n_26), .Q (hf[5]),
       .QN (UNCONNECTED35));
  DFE1 \MISR_hf_reg[6] (.C (CLK), .D (MISR_h14), .E (n_26), .Q (hf[6]),
       .QN (UNCONNECTED36));
  DFE1 \MISR_hf_reg[7] (.C (CLK), .D (MISR_h13), .E (n_26), .Q (hf[7]),
       .QN (UNCONNECTED37));
  DFE1 \MISR_hf_reg[8] (.C (CLK), .D (MISR_h12), .E (n_26), .Q (hf[8]),
       .QN (UNCONNECTED38));
  DFE1 \MISR_hf_reg[9] (.C (CLK), .D (MISR_h11), .E (n_26), .Q (hf[9]),
       .QN (UNCONNECTED39));
  DFE1 \MISR_hf_reg[10] (.C (CLK), .D (MISR_h10), .E (n_26), .Q
       (hf[10]), .QN (UNCONNECTED40));
  DFE1 \MISR_hf_reg[11] (.C (CLK), .D (MISR_h9), .E (n_26), .Q
       (hf[11]), .QN (UNCONNECTED41));
  DFE1 \MISR_hf_reg[12] (.C (CLK), .D (MISR_h8), .E (n_26), .Q
       (hf[12]), .QN (UNCONNECTED42));
  DFE1 \MISR_hf_reg[13] (.C (CLK), .D (MISR_h7), .E (n_26), .Q
       (hf[13]), .QN (UNCONNECTED43));
  DFE1 \MISR_hf_reg[14] (.C (CLK), .D (MISR_h6), .E (n_26), .Q
       (hf[14]), .QN (UNCONNECTED44));
  DFE1 \MISR_hf_reg[15] (.C (CLK), .D (MISR_h5), .E (n_26), .Q
       (hf[15]), .QN (UNCONNECTED45));
  DFE1 \MISR_hf_reg[16] (.C (CLK), .D (MISR_h4), .E (n_26), .Q
       (hf[16]), .QN (UNCONNECTED46));
  DFE1 \MISR_hf_reg[17] (.C (CLK), .D (MISR_h3), .E (n_26), .Q
       (hf[17]), .QN (UNCONNECTED47));
  DFE1 \MISR_hf_reg[18] (.C (CLK), .D (MISR_h2), .E (n_26), .Q
       (hf[18]), .QN (UNCONNECTED48));
  DFE1 \MISR_hf_reg[19] (.C (CLK), .D (MISR_h1), .E (n_26), .Q
       (hf[19]), .QN (UNCONNECTED49));
  DFE1 \MISR_hf_reg[20] (.C (CLK), .D (MISR_h0), .E (n_26), .Q
       (hf[20]), .QN (UNCONNECTED50));
  NOR21 g3694__6131(.A (n_19), .B (n_141), .Q (n_142));
  IMUX21 g3696__1881(.A (n_138), .B (Bist_count_M[6]), .S (n_205), .Q
       (n_141));
  NOR21 g3697__5115(.A (n_19), .B (n_139), .Q (n_140));
  IMUX21 g3698__7482(.A (n_137), .B (Bist_count_M[5]), .S (n_205), .Q
       (n_139));
  XOR21 g3699__4733(.A (Bist_count_M[6]), .B (n_136), .Q (n_138));
  ADD22 g3701__6161(.A (n_132), .B (Bist_count_M[5]), .CO (n_136), .S
       (n_137));
  IMUX21 g3703__9315(.A (n_133), .B (Bist_count_M[4]), .S (n_205), .Q
       (n_134));
  ADD22 g3705__9945(.A (n_126), .B (Bist_count_M[4]), .CO (n_132), .S
       (n_133));
  IMUX21 g3708__2883(.A (n_127), .B (Bist_count_M[3]), .S (n_205), .Q
       (n_130));
  OAI2111 g3711__2346(.A (scan_x), .B (n_119), .C (n_124), .D (n_15),
       .Q (n_129));
  OAI2111 g3712__1666(.A (in_x0), .B (n_118), .C (n_123), .D (n_15), .Q
       (n_128));
  ADD22 g3713__7410(.A (n_114), .B (Bist_count_M[3]), .CO (n_126), .S
       (n_127));
  NOR21 g3715__6417(.A (n_19), .B (n_120), .Q (n_125));
  NAND22 g3717__5477(.A (n_119), .B (scan_x), .Q (n_124));
  NAND22 g3718__2398(.A (n_118), .B (in_x0), .Q (n_123));
  OAI311 g3720__5107(.A (Bist_count_N[5]), .B (n_95), .C (n_203), .D
       (n_116), .Q (n_122));
  OAI222 g3721__6260(.A (n_106), .B (n_203), .C (n_110), .D (n_7), .Q
       (n_121));
  IMUX21 g3722__4319(.A (n_115), .B (Bist_count_M[2]), .S (n_205), .Q
       (n_120));
  OAI222 g3727__8428(.A (n_203), .B (n_101), .C (n_96), .D (n_11), .Q
       (n_117));
  NAND22 g3728__5526(.A (n_111), .B (Bist_count_N[5]), .Q (n_116));
  IMUX21 g3729__6783(.A (LFSR_in2_x_30), .B (LFSR_in2_x_31), .S
       (n_103), .Q (n_119));
  IMUX21 g3730__3680(.A (in_x2), .B (in_x1), .S (n_103), .Q (n_118));
  ADD22 g3731__1617(.A (n_87), .B (Bist_count_M[2]), .CO (n_114), .S
       (n_115));
  CLKIN2 g3736(.A (n_108), .Q (n_112));
  INV2 g3737(.A (n_110), .Q (n_111));
  OAI311 g3738__2802(.A (Bist_count_N[3]), .B (n_57), .C (n_203), .D
       (n_104), .Q (n_109));
  NOR40 g3739__1705(.A (n_24), .B (n_67), .C (n_30), .D (n_59), .Q
       (n_108));
  NAND31 g3740__5122(.A (n_31), .B (n_201), .C (n_93), .Q (n_107));
  AOI211 g3741__8246(.A (n_6), .B (Bist_count_N[6]), .C (n_102), .Q
       (n_106));
  AOI211 g3742__7098(.A (n_18), .B (n_95), .C (n_29), .Q (n_110));
  NAND22 g3743__6131(.A (n_90), .B (n_15), .Q (n_105));
  NAND22 g3744__1881(.A (n_97), .B (Bist_count_N[3]), .Q (n_104));
  NOR31 g3748__5115(.A (n_95), .B (n_6), .C (Bist_count_N[6]), .Q
       (n_102));
  IMUX21 g3749__7482(.A (n_89), .B (n_13), .S (Bist_count_N[4]), .Q
       (n_101));
  OAI2111 g3750__4733(.A (n_50), .B (n_1), .C (n_55), .D (n_15), .Q
       (n_100));
  OAI222 g3751__6161(.A (n_203), .B (n_71), .C (n_58), .D (n_4), .Q
       (n_99));
  IMUX20 g3752__9315(.A (n_88), .B (Bist_count_M[1]), .S (n_205), .Q
       (n_98));
  AOI211 g3753__9945(.A (n_66), .B (n_3), .C (n_203), .Q (n_103));
  INV2 g3778(.A (n_96), .Q (n_97));
  NAND31 g3779__2883(.A (n_31), .B (n_200), .C (n_52), .Q (n_94));
  NOR31 g3780__2346(.A (n_59), .B (n_53), .C (n_34), .Q (n_93));
  OAI222 g3781__1666(.A (n_39), .B (n_28), .C (n_12), .D (n_26), .Q
       (n_92));
  OAI222 g3782__7410(.A (n_58), .B (n_2), .C (n_203), .D (n_23), .Q
       (n_91));
  AOI221 g3783__6417(.A (n_17), .B (n_51), .C (MISR_h19), .D (n_25), .Q
       (n_90));
  AOI211 g3799__5477(.A (n_18), .B (n_57), .C (n_29), .Q (n_96));
  NAND22 g3802__2398(.A (n_89), .B (Bist_count_N[4]), .Q (n_95));
  ADD22 g3803__5107(.A (Bist_count_M[1]), .B (Bist_count_M[0]), .CO
       (n_87), .S (n_88));
  NAND22 g3804__6260(.A (n_49), .B (n_15), .Q (n_86));
  NOR21 g3805__4319(.A (n_19), .B (n_0), .Q (n_85));
  NAND22 g3806__8428(.A (n_54), .B (n_15), .Q (n_84));
  NAND22 g3807__5526(.A (n_56), .B (n_15), .Q (n_83));
  NAND22 g3808__6783(.A (n_38), .B (n_15), .Q (n_82));
  NAND22 g3809__3680(.A (n_44), .B (n_15), .Q (n_81));
  NAND22 g3810__1617(.A (n_48), .B (n_15), .Q (n_80));
  NAND22 g3811__2802(.A (n_47), .B (n_15), .Q (n_79));
  NAND22 g3812__1705(.A (n_46), .B (n_15), .Q (n_78));
  NAND22 g3813__5122(.A (n_45), .B (n_15), .Q (n_77));
  NOR21 g3814__8246(.A (n_13), .B (n_57), .Q (n_89));
  INV3 g3815(.A (n_64), .Q (n_76));
  INV3 g3816(.A (n_63), .Q (n_75));
  INV3 g3817(.A (n_62), .Q (n_74));
  INV3 g3818(.A (n_61), .Q (n_73));
  INV3 g3819(.A (n_60), .Q (n_72));
  AOI221 g3820__7098(.A (n_22), .B (Bist_count_N[0]), .C (n_2), .D
       (Bist_count_N[2]), .Q (n_71));
  NAND22 g3821__6131(.A (n_42), .B (n_15), .Q (n_70));
  NAND22 g3822__1881(.A (n_41), .B (n_15), .Q (n_69));
  NAND22 g3823__5115(.A (n_40), .B (n_15), .Q (n_68));
  OAI311 g3824__7482(.A (bist_start), .B (Bist_state[2]), .C
       (Bist_state[1]), .D (n_207), .Q (n_67));
  AOI2111 g3825__4733(.A (n_198), .B (Bist_count_M[2]), .C
       (Bist_count_M[6]), .D (n_197), .Q (n_66));
  NAND22 g3826__6161(.A (n_43), .B (n_15), .Q (n_65));
  AOI221 g3827__9315(.A (MISR_h6), .B (n_27), .C (MISR_h5), .D (n_25),
       .Q (n_64));
  AOI221 g3828__9945(.A (MISR_h9), .B (n_27), .C (MISR_h8), .D (n_25),
       .Q (n_63));
  AOI221 g3829__2883(.A (MISR_h13), .B (n_27), .C (MISR_h12), .D
       (n_25), .Q (n_62));
  AOI221 g3830__2346(.A (MISR_h16), .B (n_27), .C (MISR_h15), .D
       (n_25), .Q (n_61));
  AOI221 g3831__1666(.A (MISR_h2), .B (n_27), .C (MISR_h1), .D (n_25),
       .Q (n_60));
  IMUX20 g3832__7410(.A (MISR_h8), .B (MISR_h7), .S (bist_end), .Q
       (n_56));
  NAND21 g3833__6417(.A (MISR_h20), .B (n_25), .Q (n_55));
  IMUX20 g3834__5477(.A (MISR_h7), .B (MISR_h6), .S (bist_end), .Q
       (n_54));
  NOR31 g3835__2398(.A (n_193), .B (Bist_state[2]), .C (n_21), .Q
       (n_53));
  NOR21 g3836__5107(.A (n_37), .B (n_202), .Q (n_52));
  IMUX21 g3837__6260(.A (MISR_h18), .B (n_12), .S (n_199), .Q (n_51));
  OAI222 g3838__4319(.A (n_195), .B (Bist_state[2]), .C (n_189), .D
       (n_206), .Q (n_59));
  AOI211 g3840__8428(.A (n_18), .B (n_20), .C (n_29), .Q (n_58));
  NAND31 g3842__5526(.A (Bist_count_N[2]), .B (Bist_count_N[1]), .C
       (Bist_count_N[0]), .Q (n_57));
  XNR21 g3845__6783(.A (scan_out), .B (MISR_h19), .Q (n_50));
  IMUX20 g3846__3680(.A (MISR_h11), .B (MISR_h10), .S (bist_end), .Q
       (n_49));
  IMUX20 g3847__1617(.A (MISR_h12), .B (MISR_h11), .S (bist_end), .Q
       (n_48));
  IMUX20 g3848__2802(.A (MISR_h14), .B (MISR_h13), .S (bist_end), .Q
       (n_47));
  IMUX20 g3849__1705(.A (MISR_h15), .B (MISR_h14), .S (bist_end), .Q
       (n_46));
  IMUX20 g3850__5122(.A (MISR_h17), .B (MISR_h16), .S (bist_end), .Q
       (n_45));
  IMUX20 g3851__8246(.A (MISR_h18), .B (MISR_h17), .S (bist_end), .Q
       (n_44));
  IMUX20 g3852__7098(.A (MISR_h1), .B (MISR_h0), .S (bist_end), .Q
       (n_43));
  IMUX20 g3853__6131(.A (MISR_h3), .B (MISR_h2), .S (bist_end), .Q
       (n_42));
  IMUX20 g3854__1881(.A (MISR_h4), .B (MISR_h3), .S (bist_end), .Q
       (n_41));
  IMUX20 g3855__5115(.A (MISR_h5), .B (MISR_h4), .S (bist_end), .Q
       (n_40));
  XNR21 g3857__7482(.A (out_sync_err_d), .B (MISR_h17), .Q (n_39));
  IMUX20 g3858__4733(.A (MISR_h10), .B (MISR_h9), .S (bist_end), .Q
       (n_38));
  NOR21 g3859__6161(.A (bist_start), .B (n_201), .Q (n_37));
  NAND22 g3860__9315(.A (n_10), .B (n_15), .Q (n_36));
  NAND22 g3861__9945(.A (n_14), .B (n_15), .Q (n_35));
  NOR21 g3862__2883(.A (bist_start), .B (n_200), .Q (n_34));
  NAND22 g3863__2346(.A (n_8), .B (n_15), .Q (n_33));
  NAND22 g3864__1666(.A (n_9), .B (n_15), .Q (n_32));
  INV2 g3865(.A (n_30), .Q (n_31));
  INV2 g3866(.A (n_27), .Q (n_28));
  INV3 g3867(.A (n_26), .Q (n_25));
  NOR21 g3868__7410(.A (n_21), .B (n_200), .Q (n_24));
  NAND22 g3869__6417(.A (n_2), .B (Bist_count_N[0]), .Q (n_23));
  NOR21 g3870__5477(.A (Bist_count_N[2]), .B (n_2), .Q (n_22));
  NOR21 g3871__2398(.A (n_5), .B (n_194), .Q (n_30));
  NOR21 g3872__5107(.A (n_16), .B (n_192), .Q (n_29));
  NOR21 g3873__6260(.A (RST), .B (n_1), .Q (n_27));
  NAND22 g3874__4319(.A (n_1), .B (n_15), .Q (n_26));
  INV2 g3879(.A (bist_start), .Q (n_21));
  INV2 g3895(.A (Bist_count_N[0]), .Q (n_20));
  INV3 g3898(.A (n_204), .Q (n_19));
  INV2 g3899(.A (n_203), .Q (n_18));
  CLKIN2 g3901(.A (n_1), .Q (n_17));
  INV2 g3903(.A (n_206), .Q (n_16));
  INV3 g3929(.A (RST), .Q (n_15));
  BUF2 drc_bufs3935(.A (bist_end), .Q (n_1));
  XOR21 g2__8428(.A (n_205), .B (Bist_count_M[0]), .Q (n_0));
  INV0 g3936(.A (n_134), .Q (n_135));
  INV0 g3937(.A (n_130), .Q (n_131));
  INV0 g3938(.A (n_98), .Q (n_113));
endmodule

