`timescale 1ns/1ps 
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Jan  6 2024 20:26:49 WET (Jan  6 2024 20:26:49 UTC)

// Verification Directory fv/main 

module main(CLK, RST, bist_start, bist_end, pass_fail, in_k, in_j,
     in_en, out_synced_d, out_sync_err_d);
  input CLK, RST, bist_start, in_k, in_j, in_en;
  output bist_end, pass_fail, out_synced_d, out_sync_err_d;
  wire CLK, RST, bist_start, in_k, in_j, in_en;
  wire bist_end, pass_fail, out_synced_d, out_sync_err_d;
  wire [2:0] circuito_scan_fs_state;
  wire [7:0] hf;
  wire [2:0] Bist_state;
  wire [3:0] Bist_count_N;
  wire [3:0] Bist_count_M;
  wire Bist_n_13, Bist_n_15, Bist_n_23, Bist_n_69, Bist_n_684,
       Bist_n_740, Bist_n_743, Bist_n_745;
  wire Bist_n_746, Bist_n_749, Bist_n_810, MISR_h0, MISR_h1, MISR_h2,
       MISR_h3, MISR_h4;
  wire MISR_h5, MISR_h6, MISR_h7, UNCONNECTED, UNCONNECTED0,
       UNCONNECTED1, UNCONNECTED2, UNCONNECTED3;
  wire UNCONNECTED4, UNCONNECTED5, UNCONNECTED6, UNCONNECTED7,
       UNCONNECTED8, UNCONNECTED9, UNCONNECTED10, UNCONNECTED11;
  wire UNCONNECTED12, UNCONNECTED13, UNCONNECTED14, UNCONNECTED15,
       UNCONNECTED16, UNCONNECTED17, UNCONNECTED18, UNCONNECTED19;
  wire UNCONNECTED20, UNCONNECTED21, UNCONNECTED22, UNCONNECTED23,
       circuito_scan_n_0, circuito_scan_n_1, circuito_scan_n_10,
       circuito_scan_n_17;
  wire circuito_scan_n_19, in_x0, in_x1, in_x2, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, scan_out;
  DFS3 \circuito_scan_fs_state_reg[0] (.C (CLK), .D (n_92), .SD
       (in_x0), .SE (n_93), .Q (circuito_scan_n_0), .QN
       (circuito_scan_fs_state[0]));
  JKS3 \circuito_scan_fs_state_reg[1] (.C (CLK), .J
       (circuito_scan_n_17), .K (circuito_scan_n_10), .SD
       (circuito_scan_n_0), .SE (n_93), .Q (circuito_scan_fs_state[1]),
       .QN (circuito_scan_n_1));
  DFS3 \circuito_scan_fs_state_reg[2] (.C (CLK), .D
       (circuito_scan_n_19), .SD (circuito_scan_n_1), .SE (n_93), .Q
       (circuito_scan_fs_state[2]), .QN (scan_out));
  CLKIN2 g1529(.A (circuito_scan_n_10), .Q (n_92));
  INV3 g1530(.A (Bist_n_13), .Q (n_93));
  DLQ3 Comp_passnfail_reg(.GN (Bist_n_15), .D (n_91), .Q (pass_fail));
  NOR40 g2011__2398(.A (hf[0]), .B (hf[1]), .C (n_86), .D (n_90), .Q
       (n_91));
  NAND40 g2012__5107(.A (hf[5]), .B (hf[6]), .C (hf[7]), .D (hf[4]), .Q
       (n_90));
  DF3 \MISR_hf_reg[7] (.C (CLK), .D (MISR_h7), .Q (hf[7]), .QN
       (UNCONNECTED));
  DF3 MISR_h7_reg(.C (CLK), .D (n_89), .Q (MISR_h7), .QN
       (UNCONNECTED0));
  DF3 \MISR_hf_reg[6] (.C (CLK), .D (MISR_h6), .Q (UNCONNECTED1), .QN
       (hf[6]));
  NOR21 g2016__6260(.A (MISR_h6), .B (MISR_h5), .Q (n_89));
  DF3 MISR_h6_reg(.C (CLK), .D (n_88), .Q (MISR_h6), .QN
       (UNCONNECTED2));
  DF3 \MISR_hf_reg[5] (.C (CLK), .D (MISR_h5), .Q (UNCONNECTED3), .QN
       (hf[5]));
  NOR21 g2019__4319(.A (MISR_h4), .B (MISR_h5), .Q (n_88));
  DF3 MISR_h5_reg(.C (CLK), .D (n_87), .Q (MISR_h5), .QN
       (UNCONNECTED4));
  DF3 \MISR_hf_reg[4] (.C (CLK), .D (MISR_h4), .Q (hf[4]), .QN
       (UNCONNECTED5));
  NOR21 g2022__8428(.A (MISR_h3), .B (MISR_h4), .Q (n_87));
  DF3 MISR_h4_reg(.C (CLK), .D (n_85), .Q (MISR_h4), .QN
       (UNCONNECTED6));
  NAND20 g2024__5526(.A (hf[2]), .B (hf[3]), .Q (n_86));
  DF3 \MISR_hf_reg[3] (.C (CLK), .D (MISR_h3), .Q (UNCONNECTED7), .QN
       (hf[3]));
  NOR21 g2026__6783(.A (MISR_h3), .B (MISR_h2), .Q (n_85));
  DF3 MISR_h3_reg(.C (CLK), .D (n_84), .Q (MISR_h3), .QN
       (UNCONNECTED8));
  DF3 \MISR_hf_reg[1] (.C (CLK), .D (MISR_h1), .Q (UNCONNECTED9), .QN
       (hf[1]));
  NOR21 g2029__3680(.A (MISR_h1), .B (MISR_h2), .Q (n_84));
  DF3 MISR_h1_reg(.C (CLK), .D (n_83), .Q (MISR_h1), .QN
       (UNCONNECTED10));
  NOR21 g2031__1617(.A (MISR_h0), .B (out_synced_d), .Q (n_83));
  OAI222 g2032__2802(.A (n_82), .B (n_77), .C (n_79), .D
       (circuito_scan_fs_state[0]), .Q (out_sync_err_d));
  NOR31 g2033__1705(.A (n_80), .B (circuito_scan_fs_state[0]), .C
       (n_55), .Q (out_synced_d));
  OAI222 g2034__5122(.A (n_81), .B (n_67), .C (circuito_scan_n_10), .D
       (n_55), .Q (circuito_scan_n_19));
  AOI221 g2035__8246(.A (n_78), .B (n_66), .C
       (circuito_scan_fs_state[1]), .D (circuito_scan_fs_state[0]), .Q
       (n_82));
  CLKIN3 g2036(.A (circuito_scan_n_17), .Q (n_81));
  NOR21 g2037__7098(.A (RST), .B (n_78), .Q (circuito_scan_n_17));
  AOI221 g2038__6131(.A (n_77), .B (n_72), .C (n_74), .D
       (circuito_scan_fs_state[1]), .Q (n_80));
  NAND31 g2039__1881(.A (n_77), .B (circuito_scan_fs_state[0]), .C
       (n_57), .Q (circuito_scan_n_10));
  NAND22 g2040__5115(.A (n_76), .B (n_55), .Q (n_79));
  NAND22 g2041__7482(.A (n_75), .B (n_56), .Q (n_78));
  NOR21 g2042__4733(.A (n_73), .B (n_71), .Q (n_77));
  INV2 g2043(.A (n_75), .Q (n_76));
  NOR21 g2044__6161(.A (n_72), .B (n_71), .Q (n_75));
  INV2 g2045(.A (n_73), .Q (n_74));
  OAI2110 g2046__9315(.A (Bist_state[0]), .B (n_54), .C (Bist_n_810),
       .D (Bist_n_743), .Q (bist_end));
  IMUX21 g2047__9945(.A (in_x0), .B (in_k), .S (Bist_n_13), .Q (n_73));
  IMUX21 g2048__2883(.A (in_x1), .B (in_j), .S (Bist_n_13), .Q (n_72));
  IMUX21 g2049__2346(.A (in_x2), .B (in_en), .S (Bist_n_13), .Q (n_71));
  INV2 g2050(.A (n_70), .Q (Bist_n_810));
  NOR21 g2051__1666(.A (Bist_n_684), .B (Bist_n_740), .Q (n_70));
  NAND31 g2052__7410(.A (Bist_n_69), .B (n_68), .C (Bist_n_23), .Q
       (Bist_n_13));
  NAND22 g2053__6417(.A (Bist_n_69), .B (n_65), .Q (Bist_n_740));
  NAND22 g2054__5477(.A (n_69), .B (Bist_count_N[3]), .Q (Bist_n_69));
  CLKIN2 g2055(.A (Bist_n_746), .Q (n_69));
  INV2 g2056(.A (Bist_n_684), .Q (n_68));
  DF3 LFSR_in_x0_reg(.C (CLK), .D (n_62), .Q (in_x0), .QN
       (UNCONNECTED11));
  NAND22 g2058__2398(.A (n_64), .B (Bist_count_N[0]), .Q (Bist_n_746));
  NAND31 g2059__5107(.A (n_54), .B (Bist_state[0]), .C (Bist_state[1]),
       .Q (Bist_n_684));
  INV2 g2060(.A (n_66), .Q (n_67));
  INV3 g2061(.A (n_65), .Q (Bist_n_23));
  NAND22 g2062__6260(.A (n_63), .B (n_58), .Q (Bist_n_15));
  IMUX21 g2063__4319(.A (n_55), .B (circuito_scan_fs_state[2]), .S
       (circuito_scan_fs_state[1]), .Q (n_66));
  NOR40 g2064__8428(.A (Bist_count_M[2]), .B (Bist_count_M[1]), .C
       (n_60), .D (n_61), .Q (n_65));
  INV2 g2065(.A (n_64), .Q (Bist_n_749));
  DF3 \MISR_hf_reg[0] (.C (CLK), .D (MISR_h0), .Q (hf[0]), .QN
       (UNCONNECTED12));
  DF3 \MISR_hf_reg[2] (.C (CLK), .D (MISR_h2), .Q (UNCONNECTED13), .QN
       (hf[2]));
  NOR21 g2068__5526(.A (Bist_count_N[1]), .B (Bist_count_N[2]), .Q
       (n_64));
  INV3 g2069(.A (n_63), .Q (Bist_n_743));
  NAND22 g2070__6783(.A (n_59), .B (n_57), .Q (n_62));
  NAND22 g2071__3680(.A (n_54), .B (Bist_state[0]), .Q (Bist_n_745));
  NOR21 g2072__1617(.A (Bist_state[1]), .B (n_54), .Q (n_63));
  INV3 g2073(.A (Bist_count_M[3]), .Q (n_61));
  INV3 g2074(.A (Bist_count_M[0]), .Q (n_60));
  INV2 g2075(.A (in_x1), .Q (n_59));
  INV2 g2076(.A (Bist_state[0]), .Q (n_58));
  CLKIN3 g2077(.A (RST), .Q (n_57));
  INV2 g2078(.A (circuito_scan_fs_state[0]), .Q (n_56));
  INV3 g2079(.A (circuito_scan_fs_state[2]), .Q (n_55));
  INV3 g2080(.A (Bist_state[2]), .Q (n_54));
  DFC3 \Bist_count_M_reg[3] (.RN (n_8), .C (CLK), .D (n_53), .Q
       (Bist_count_M[3]), .QN (UNCONNECTED14));
  DFC3 \Bist_count_N_reg[3] (.RN (n_8), .C (CLK), .D (n_51), .Q
       (Bist_count_N[3]), .QN (n_5));
  NOR21 g1957__2802(.A (n_9), .B (n_52), .Q (n_53));
  DFC3 \Bist_count_M_reg[2] (.RN (n_8), .C (CLK), .D (n_50), .Q
       (Bist_count_M[2]), .QN (UNCONNECTED15));
  IMUX21 g1959__1705(.A (n_46), .B (Bist_count_M[3]), .S (Bist_n_69),
       .Q (n_52));
  OAI221 g1960__5122(.A (Bist_n_13), .B (n_47), .C (n_18), .D (n_16),
       .Q (n_51));
  DFC3 \Bist_count_N_reg[2] (.RN (n_8), .C (CLK), .D (n_49), .Q
       (Bist_count_N[2]), .QN (n_3));
  OAI221 g1963__8246(.A (Bist_n_13), .B (n_45), .C (n_18), .D (n_3), .Q
       (n_49));
  IMUX21 g1964__7098(.A (n_44), .B (Bist_count_M[2]), .S (Bist_n_69),
       .Q (n_48));
  XNR21 g1965__6131(.A (Bist_count_N[3]), .B (n_41), .Q (n_47));
  XOR21 g1966__1881(.A (Bist_count_M[3]), .B (n_43), .Q (n_46));
  DFC3 \Bist_count_M_reg[1] (.RN (n_8), .C (CLK), .D (n_40), .Q
       (Bist_count_M[1]), .QN (UNCONNECTED16));
  INV3 g1968(.A (n_42), .Q (n_45));
  ADD22 g1969__5115(.A (n_30), .B (Bist_count_M[2]), .CO (n_43), .S
       (n_44));
  ADD22 g1970__7482(.A (n_32), .B (Bist_count_N[2]), .CO (n_41), .S
       (n_42));
  DFC3 \Bist_count_N_reg[1] (.RN (n_8), .C (CLK), .D (n_38), .Q
       (Bist_count_N[1]), .QN (n_4));
  NOR21 g1972__4733(.A (n_9), .B (n_37), .Q (n_40));
  DFC3 \Bist_state_reg[0] (.RN (n_8), .C (CLK), .D (n_39), .Q
       (Bist_state[0]), .QN (n_1));
  DFC3 \Bist_state_reg[1] (.RN (n_8), .C (CLK), .D (n_36), .Q
       (Bist_state[1]), .QN (UNCONNECTED17));
  JKC3 \Bist_count_N_reg[0] (.RN (n_8), .C (CLK), .J (n_13), .K (n_20),
       .Q (Bist_count_N[0]), .QN (UNCONNECTED18));
  OAI2111 g1976__6161(.A (Bist_state[2]), .B (n_22), .C (n_35), .D
       (Bist_n_15), .Q (n_39));
  OAI221 g1977__9315(.A (Bist_n_13), .B (n_34), .C (n_18), .D (n_4), .Q
       (n_38));
  IMUX21 g1978__9945(.A (n_31), .B (Bist_count_M[1]), .S (Bist_n_69),
       .Q (n_37));
  DF3 MISR_h2_reg(.C (CLK), .D (n_27), .Q (MISR_h2), .QN
       (UNCONNECTED19));
  DFC3 \Bist_state_reg[2] (.RN (n_8), .C (CLK), .D (n_26), .Q
       (Bist_state[2]), .QN (UNCONNECTED20));
  DFC3 \Bist_count_M_reg[0] (.RN (n_8), .C (CLK), .D (n_29), .Q
       (Bist_count_M[0]), .QN (UNCONNECTED21));
  NAND22 g1982__2883(.A (n_24), .B (n_25), .Q (n_36));
  AOI221 g1983__2346(.A (n_22), .B (Bist_state[2]), .C (Bist_n_740), .D
       (n_7), .Q (n_35));
  DF3 LFSR_in_x2_reg(.C (CLK), .D (n_28), .Q (in_x2), .QN (n_2));
  INV3 g1985(.A (n_33), .Q (n_34));
  ADD22 g1986__1666(.A (Bist_count_N[1]), .B (Bist_count_N[0]), .CO
       (n_32), .S (n_33));
  ADD22 g1987__7410(.A (Bist_count_M[1]), .B (Bist_count_M[0]), .CO
       (n_30), .S (n_31));
  NOR21 g1988__6417(.A (n_9), .B (n_0), .Q (n_29));
  NAND22 g1989__5477(.A (n_19), .B (n_8), .Q (n_28));
  NOR21 g1990__2398(.A (scan_out), .B (n_23), .Q (n_27));
  NAND31 g1991__5107(.A (Bist_n_810), .B (n_21), .C (Bist_n_743), .Q
       (n_26));
  AOI221 g1992__6260(.A (n_12), .B (bist_start), .C (n_10), .D
       (Bist_state[2]), .Q (n_25));
  OAI212 g1993__4319(.A (Bist_n_745), .B (Bist_n_740), .C
       (Bist_state[1]), .Q (n_24));
  NOR21 g1994__8428(.A (MISR_h2), .B (n_11), .Q (n_23));
  DF3 LFSR_in_x1_reg(.C (CLK), .D (n_14), .Q (in_x1), .QN
       (UNCONNECTED22));
  DF3 MISR_h0_reg(.C (CLK), .D (n_15), .Q (MISR_h0), .QN
       (UNCONNECTED23));
  OAI212 g1998__5526(.A (n_6), .B (Bist_state[0]), .C (Bist_state[2]),
       .Q (n_21));
  OAI212 g1999__6783(.A (Bist_n_749), .B (n_5), .C (n_17), .Q (n_20));
  XNR21 g2000__3680(.A (in_x0), .B (in_x2), .Q (n_19));
  MUX22 g2001__1617(.A (bist_start), .B (Bist_state[0]), .S
       (Bist_state[1]), .Q (n_22));
  INV3 g2002(.A (n_17), .Q (n_18));
  NAND22 g2003__2802(.A (Bist_n_746), .B (Bist_count_N[3]), .Q (n_16));
  NOR21 g2004__1705(.A (MISR_h1), .B (out_sync_err_d), .Q (n_15));
  NAND22 g2005__5122(.A (n_2), .B (n_8), .Q (n_14));
  NOR21 g2006__8246(.A (n_9), .B (n_7), .Q (n_17));
  NOR21 g2007__7098(.A (n_9), .B (Bist_n_684), .Q (n_13));
  NOR21 g2008__6131(.A (Bist_state[1]), .B (Bist_n_745), .Q (n_12));
  NOR21 g2009__1881(.A (MISR_h1), .B (MISR_h0), .Q (n_11));
  NOR21 g2010__5115(.A (bist_start), .B (n_1), .Q (n_10));
  INV3 g2025(.A (Bist_n_23), .Q (n_9));
  CLKIN3 g2027(.A (RST), .Q (n_8));
  INV3 g2028(.A (Bist_n_684), .Q (n_7));
  INV2 g2081(.A (bist_start), .Q (n_6));
  XOR21 g2__7482(.A (Bist_n_69), .B (Bist_count_M[0]), .Q (n_0));
  INV0 g2082(.A (n_48), .Q (n_50));
endmodule

