fault -inject -time 0 -type SA0 {main_test_bench.under_test.CLK}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_92}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.in_x0}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_93}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.circuito_scan_n_0}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.circuito_scan_fs_state[0]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.circuito_scan_n_17}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.circuito_scan_n_10}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.circuito_scan_fs_state[1]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.circuito_scan_n_1}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.circuito_scan_n_19}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.circuito_scan_fs_state[2]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.scan_out}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_11}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_n_13}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_68}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_n_15}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_58}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.hf[3]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.pass_fail}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.hf[0]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.hf[1]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_86}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_90}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h7}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_89}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h6}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h5}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_88}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h4}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_87}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h3}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_85}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h2}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_84}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h1}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_83}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h0}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.out_synced_d}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_82}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_77}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_79}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_76}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.out_sync_err_d}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_80}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_55}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_81}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_67}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_78}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_56}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_66}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.RST}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_72}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_74}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_57}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_75}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_73}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_71}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_state[0]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_54}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_70}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_n_743}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.bist_end}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.in_k}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.in_x1}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.in_j}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.in_x2}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.in_en}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_n_684}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_n_740}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_n_69}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_69}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_n_23}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_61}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_count_N[3]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_n_746}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_62}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_59}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_64}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_count_N[0]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_state[1]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_63}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_count_M[2]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_count_M[1]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_60}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_n_749}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_count_N[1]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_count_N[2]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_n_745}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_count_M[3]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_count_M[0]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_state[2]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_8}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_52}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_51}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_5}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_9}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_50}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_46}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_47}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_18}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_16}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_49}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_3}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_42}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_44}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_48}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_41}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_43}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_37}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_30}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_32}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_38}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_4}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_39}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_35}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_1}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_10}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_36}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_25}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_13}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_20}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_22}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_33}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_31}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_26}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_21}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_0}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_7}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_28}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_19}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_14}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_12}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.bist_start}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_15}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_6}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_17}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.CLK}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_92}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.in_x0}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_93}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.circuito_scan_n_0}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.circuito_scan_fs_state[0]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.circuito_scan_n_17}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.circuito_scan_n_10}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.circuito_scan_fs_state[1]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.circuito_scan_n_1}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.circuito_scan_n_19}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.circuito_scan_fs_state[2]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_23}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_11}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_68}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_58}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_91}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.hf[3]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.pass_fail}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.hf[5]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.hf[6]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.hf[7]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.hf[4]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h7}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_89}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h6}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h5}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_88}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h4}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_87}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h3}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_85}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.hf[2]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h2}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_84}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h1}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_83}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h0}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.out_synced_d}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_82}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_77}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_76}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.out_sync_err_d}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_80}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_55}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_67}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_56}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_66}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.RST}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_72}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_74}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_57}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_75}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_73}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_71}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_state[0]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_54}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_n_810}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_70}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_n_743}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.bist_end}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.in_k}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.in_x1}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.in_j}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.in_x2}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.in_en}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_n_684}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_n_740}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_69}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_n_23}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_65}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_61}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_count_N[3]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_n_746}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_59}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_64}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_count_N[0]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_state[1]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_63}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_count_M[2]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_count_M[1]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_n_749}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_count_N[1]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_count_N[2]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_n_745}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_count_M[3]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_count_M[0]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_state[2]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_8}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_53}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_52}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_51}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_5}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_9}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_50}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_46}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_47}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_18}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_16}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_49}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_3}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_45}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_42}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_44}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_48}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_41}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_43}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_40}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_37}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_30}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_32}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_38}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_4}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_35}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_10}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_25}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_13}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_20}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_22}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_34}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_33}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_31}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_27}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_21}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_29}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_0}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_24}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_7}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_19}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_2}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_14}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_12}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.bist_start}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_15}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_6}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_17}
