`timescale 1ns / 100ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Jan  6 2024 14:38:36 WET (Jan  6 2024 14:38:36 UTC)

// Verification Directory fv/circuito12 

module circuito12(clk, rst, k, j, rx_en, synced_d, sync_err_d);
  input clk, rst, k, j, rx_en;
  output synced_d, sync_err_d;
  wire clk, rst, k, j, rx_en;
  wire synced_d, sync_err_d;
  wire [2:0] fs_state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, n_0, n_1, n_2, n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_12, n_13;
  wire n_14, n_15, n_16;
  DF3 \fs_state_reg[2] (.C (clk), .D (n_15), .Q (fs_state[2]), .QN
       (UNCONNECTED));
  OAI310 g935__2398(.A (n_3), .B (fs_state[0]), .C (fs_state[2]), .D
       (n_16), .Q (sync_err_d));
  DFS1 \fs_state_reg[1] (.C (clk), .D (n_13), .SD (n_12), .SE
       (fs_state[1]), .Q (fs_state[1]), .QN (UNCONNECTED0));
  NAND20 g937__5107(.A (n_10), .B (n_5), .Q (n_16));
  INV2 g938(.A (n_14), .Q (n_15));
  AOI221 g940__6260(.A (n_8), .B (n_13), .C (fs_state[2]), .D (n_12),
       .Q (n_14));
  NOR30 g939__4319(.A (n_1), .B (fs_state[0]), .C (n_6), .Q (synced_d));
  INV0 g942(.A (n_9), .Q (n_10));
  AOI220 g943__8428(.A (n_8), .B (n_7), .C (fs_state[0]), .D
       (fs_state[1]), .Q (n_9));
  NOR21 g944__5526(.A (rst), .B (n_7), .Q (n_13));
  DF3 \fs_state_reg[0] (.C (clk), .D (n_12), .Q (UNCONNECTED1), .QN
       (fs_state[0]));
  AOI210 g945__6783(.A (fs_state[1]), .B (k), .C (n_2), .Q (n_6));
  NOR31 g946__3680(.A (n_4), .B (n_5), .C (rst), .Q (n_12));
  NAND22 g948__1617(.A (n_4), .B (n_3), .Q (n_7));
  NOR20 g947__2802(.A (j), .B (n_5), .Q (n_2));
  IMUX21 g949__1705(.A (n_1), .B (fs_state[2]), .S (fs_state[1]), .Q
       (n_8));
  INV0 g950(.A (n_0), .Q (n_3));
  NAND20 g952__5122(.A (k), .B (rx_en), .Q (n_5));
  NAND20 g951__8246(.A (j), .B (rx_en), .Q (n_0));
  INV3 g953(.A (fs_state[2]), .Q (n_1));
  INV3 g954(.A (fs_state[0]), .Q (n_4));
endmodule

