fault -inject -time 0 -type SA0 {main_test_bench.under_test.CLK}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_190}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.scan_x}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_191}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.circuito_scan_n_0}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.circuito_scan_fs_state[0]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.circuito_scan_n_17}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.circuito_scan_n_10}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_147}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.circuito_scan_fs_state[1]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.circuito_scan_n_1}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.circuito_scan_n_19}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.circuito_scan_fs_state[2]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.scan_out}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_203}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_168}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_196}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_189}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_199}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_179}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.out_synced_d}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_count_N[3]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_187}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_153}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.hf[17]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_184}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_183}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_182}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_176}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_178}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_175}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.out_sync_err_d}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_145}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_181}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_159}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_144}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_177}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_158}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.RST}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_170}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_173}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_174}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_172}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_171}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_169}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_200}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_201}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.bist_end}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.in_x0}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.in_k}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.in_x2}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.in_en}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.in_x1}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.in_j}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_202}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_206}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_207}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.pass_fail}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_162}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_165}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_205}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_192}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_154}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_163}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_164}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_204}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_152}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_151}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_count_M[5]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_count_M[6]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_count_M[2]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_count_N[0]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.hf[1]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.hf[11]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_150}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_state[2]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_149}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_143}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_146}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_194}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.hf[10]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.hf[9]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.hf[8]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.hf[7]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_count_N[4]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_count_N[2]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_count_N[1]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.hf[15]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.hf[14]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.hf[13]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_count_N[6]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_count_N[5]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_state[0]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_state[1]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_count_M[3]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_count_M[4]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_198}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_193}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_53}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_34}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_195}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.hf[19]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_count_M[0]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.Bist_count_M[1]}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_15}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_0}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_113}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_120}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_131}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_135}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_139}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_66}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_141}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_18}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_16}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_91}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_2}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_99}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_4}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_109}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_104}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_97}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_13}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_117}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_11}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_122}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_116}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_111}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_6}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_121}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_7}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_67}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_107}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_94}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_37}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_5}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_30}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_36}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_35}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.LFSR_in2_x_30}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_10}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_129}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_124}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.LFSR_in2_x_31}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_14}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_33}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_32}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_8}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_128}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_123}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_9}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_65}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_43}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h0}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_60}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h1}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_70}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_42}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h2}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_69}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_41}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h3}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_68}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_40}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h4}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_64}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h5}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_84}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_54}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h6}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_83}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_56}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h7}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_63}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h8}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_82}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_38}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h9}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_86}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_49}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h10}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_80}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_48}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h11}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_62}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h12}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_79}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_47}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h13}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_78}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_46}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h14}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_61}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h15}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_77}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_45}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h16}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_81}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_44}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h17}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_92}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h18}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_12}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_105}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_90}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h19}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_100}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_55}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.MISR_h20}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_26}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_19}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_138}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_137}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_136}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_132}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_133}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_134}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_126}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_127}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_130}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_119}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_118}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_114}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_95}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_102}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_110}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_115}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_101}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_96}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_103}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_87}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_57}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_24}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_59}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_31}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_89}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_50}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_1}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_71}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_58}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_88}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_98}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_39}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_28}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_23}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_51}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_25}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_22}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.bist_start}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_27}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_21}
fault -inject -time 0 -type SA0 {main_test_bench.under_test.n_20}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.CLK}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_190}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.scan_x}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_191}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.circuito_scan_n_0}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.circuito_scan_fs_state[0]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.circuito_scan_n_17}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_147}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.circuito_scan_fs_state[1]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.circuito_scan_n_1}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.circuito_scan_n_19}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.circuito_scan_fs_state[2]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.scan_out}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_168}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_196}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_189}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_179}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.out_synced_d}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_count_N[3]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_153}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_186}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.hf[17]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_185}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_182}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_176}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_175}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.out_sync_err_d}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_180}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_145}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_159}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_144}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_177}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_158}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.RST}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_170}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_173}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_174}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_172}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_171}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_169}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_200}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_201}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.bist_end}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.in_x0}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.in_k}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.in_x2}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.in_en}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.in_x1}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.in_j}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_202}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_206}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_207}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_167}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.pass_fail}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_162}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_166}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_165}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_192}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_157}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_204}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_197}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_152}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_151}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_count_M[5]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_count_M[6]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_count_M[2]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_156}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_count_N[0]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_155}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_148}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.hf[18]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.hf[12]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_161}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.hf[0]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.hf[2]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_150}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_state[2]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_149}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_143}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_146}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_194}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_count_N[4]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_count_N[2]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_count_N[1]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.hf[4]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.hf[5]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_count_N[6]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_count_N[5]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_state[0]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_state[1]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_count_M[3]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_count_M[4]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_198}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_34}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_195}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_count_M[0]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.Bist_count_M[1]}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_15}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_85}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_0}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_113}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_125}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_120}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_131}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_135}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_140}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_139}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_3}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_66}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_142}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_141}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_18}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_29}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_16}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_91}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_2}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_99}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_4}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_97}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_13}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_117}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_11}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_111}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_6}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_121}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_7}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_112}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_108}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_67}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_37}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_30}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_36}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_35}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.LFSR_in2_x_30}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_10}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_124}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.LFSR_in2_x_31}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_14}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_33}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_32}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_8}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_123}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_9}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_43}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h0}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_72}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_60}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h1}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_42}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h2}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_41}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h3}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_40}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h4}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_76}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_64}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h5}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_54}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h6}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_56}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h7}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_75}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_63}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h8}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_38}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h9}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_49}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h10}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_48}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h11}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_74}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_62}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h12}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_47}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h13}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_46}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h14}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_73}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_61}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h15}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_45}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h16}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_44}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h17}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_92}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h18}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_12}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_90}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h19}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_55}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.MISR_h20}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_26}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_19}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_138}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_137}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_136}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_132}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_133}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_134}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_126}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_127}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_130}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_119}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_118}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_114}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_95}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_106}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_102}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_110}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_115}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_101}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_96}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_103}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_87}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_57}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_59}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_31}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_93}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_89}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_50}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_1}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_71}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_58}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_88}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_98}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_52}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_28}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_23}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_17}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_51}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_25}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_22}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.bist_start}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_27}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_21}
fault -inject -time 0 -type SA1 {main_test_bench.under_test.n_20}
