
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Dec 18 2023 12:14:13 WET (Dec 18 2023 12:14:13 UTC)

// Verification Directory fv/circuito12 

module circuito12(clk, rst, k, j, rx_en, synced_d, sync_err_d, scan_en,
     scan_in, scan_out);
  input clk, rst, k, j, rx_en, scan_en, scan_in;
  output synced_d, sync_err_d, scan_out;
  wire clk, rst, k, j, rx_en, scan_en, scan_in;
  wire synced_d, sync_err_d, scan_out;
  wire [2:0] fs_state;
  wire n_0, n_1, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_16, n_17;
  wire n_18, n_19, n_20;
  DFS1 \fs_state_reg[2] (.C (clk), .D (n_19), .SD (n_1), .SE (scan_en),
       .Q (fs_state[2]), .QN (scan_out));
  JKS3 \fs_state_reg[1] (.C (clk), .J (n_17), .K (n_10), .SD (n_0), .SE
       (scan_en), .Q (fs_state[1]), .QN (n_1));
  OAI310 g935__2398(.A (n_6), .B (fs_state[0]), .C (fs_state[2]), .D
       (n_20), .Q (sync_err_d));
  NAND20 g937__5107(.A (n_14), .B (n_8), .Q (n_20));
  INV2 g938(.A (n_18), .Q (n_19));
  AOI221 g940__6260(.A (n_12), .B (n_17), .C (fs_state[2]), .D (n_16),
       .Q (n_18));
  DFS1 \fs_state_reg[0] (.C (clk), .D (n_16), .SD (scan_in), .SE
       (scan_en), .Q (n_0), .QN (fs_state[0]));
  NOR30 g939__4319(.A (n_4), .B (fs_state[0]), .C (n_9), .Q (synced_d));
  INV0 g942(.A (n_13), .Q (n_14));
  AOI220 g943__8428(.A (n_12), .B (n_11), .C (fs_state[1]), .D
       (fs_state[0]), .Q (n_13));
  NOR21 g944__5526(.A (rst), .B (n_11), .Q (n_17));
  INV2 g945(.A (n_16), .Q (n_10));
  AOI210 g946__6783(.A (fs_state[1]), .B (k), .C (n_5), .Q (n_9));
  NOR31 g947__3680(.A (n_7), .B (n_8), .C (rst), .Q (n_16));
  NAND22 g949__1617(.A (n_7), .B (n_6), .Q (n_11));
  NOR20 g948__2802(.A (j), .B (n_8), .Q (n_5));
  IMUX21 g950__1705(.A (n_4), .B (fs_state[2]), .S (fs_state[1]), .Q
       (n_12));
  INV0 g951(.A (n_3), .Q (n_6));
  NAND20 g953__5122(.A (k), .B (rx_en), .Q (n_8));
  NAND20 g952__8246(.A (j), .B (rx_en), .Q (n_3));
  INV3 g955(.A (fs_state[0]), .Q (n_7));
  INV2 g954(.A (fs_state[2]), .Q (n_4));
endmodule

