`timescale 1ns/1ps 
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Jan  7 2024 15:30:30 WET (Jan  7 2024 15:30:30 UTC)

// Verification Directory fv/main 

module main(CLK, RST, bist_start, bist_end, pass_fail, in_k, in_j,
     in_en, out_synced_d, out_sync_err_d);
  input CLK, RST, bist_start, in_k, in_j, in_en;
  output bist_end, pass_fail, out_synced_d, out_sync_err_d;
  wire CLK, RST, bist_start, in_k, in_j, in_en;
  wire bist_end, pass_fail, out_synced_d, out_sync_err_d;
  wire [2:0] circuito_scan_fs_state;
  wire [20:0] hf;
  wire [6:0] Bist_count_N;
  wire [2:0] Bist_state;
  wire [6:0] Bist_count_M;
  wire Bist_n_350, Finish, MISR_h0, MISR_h1, MISR_h2, MISR_h3, MISR_h4,
       MISR_h5;
  wire MISR_h6, MISR_h7, MISR_h8, MISR_h9, MISR_h10, MISR_h11,
       MISR_h12, MISR_h13;
  wire MISR_h14, MISR_h15, MISR_h16, MISR_h17, MISR_h18, MISR_h19,
       MISR_h20, UNCONNECTED;
  wire UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, UNCONNECTED3,
       UNCONNECTED4, UNCONNECTED5, UNCONNECTED6, UNCONNECTED7;
  wire UNCONNECTED8, UNCONNECTED9, UNCONNECTED10, UNCONNECTED11,
       UNCONNECTED12, UNCONNECTED13, UNCONNECTED14, UNCONNECTED15;
  wire UNCONNECTED16, UNCONNECTED17, UNCONNECTED18, UNCONNECTED19,
       UNCONNECTED20, UNCONNECTED21, UNCONNECTED22, UNCONNECTED23;
  wire UNCONNECTED24, UNCONNECTED25, UNCONNECTED26, UNCONNECTED27,
       UNCONNECTED28, UNCONNECTED29, UNCONNECTED30, UNCONNECTED31;
  wire UNCONNECTED32, UNCONNECTED33, UNCONNECTED34, UNCONNECTED35,
       UNCONNECTED36, UNCONNECTED37, UNCONNECTED38, UNCONNECTED39;
  wire UNCONNECTED40, UNCONNECTED41, UNCONNECTED42, UNCONNECTED43,
       UNCONNECTED44, UNCONNECTED45, UNCONNECTED46, UNCONNECTED47;
  wire UNCONNECTED48, UNCONNECTED49, UNCONNECTED50, UNCONNECTED51,
       circuito_scan_n_0, circuito_scan_n_1, circuito_scan_n_10,
       circuito_scan_n_17;
  wire circuito_scan_n_19, in_x0, in_x1, in_x2, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_123;
  wire n_124, n_125, n_126, n_127, n_128, n_129, n_130, n_131;
  wire n_132, n_133, n_134, n_135, n_136, n_137, n_138, n_139;
  wire n_140, n_141, n_142, n_143, n_144, n_145, n_146, n_147;
  wire n_148, n_149, n_150, n_151, n_152, n_153, n_154, n_155;
  wire n_156, n_157, n_158, n_159, n_160, n_161, n_162, n_163;
  wire n_164, n_165, n_166, n_167, n_168, n_169, n_170, n_171;
  wire n_172, n_173, n_174, n_175, n_176, n_177, n_179, n_180;
  wire n_181, n_182, n_183, n_184, n_185, n_186, n_187, n_188;
  wire n_189, scan_out;
  DFS3 \circuito_scan_fs_state_reg[0] (.C (CLK), .D (n_180), .SD
       (in_x0), .SE (n_181), .Q (circuito_scan_n_0), .QN
       (circuito_scan_fs_state[0]));
  JKS3 \circuito_scan_fs_state_reg[1] (.C (CLK), .J
       (circuito_scan_n_17), .K (circuito_scan_n_10), .SD
       (circuito_scan_n_0), .SE (n_181), .Q
       (circuito_scan_fs_state[1]), .QN (circuito_scan_n_1));
  DFS3 \circuito_scan_fs_state_reg[2] (.C (CLK), .D
       (circuito_scan_n_19), .SD (circuito_scan_n_1), .SE (n_181), .Q
       (circuito_scan_fs_state[2]), .QN (scan_out));
  INV2 g2368(.A (circuito_scan_n_10), .Q (n_180));
  INV2 g2371(.A (n_188), .Q (n_181));
  INV2 g2369(.A (n_183), .Q (n_179));
  INV0 g2372(.A (n_189), .Q (out_synced_d));
  CLKIN2 g2370(.A (n_182), .Q (n_177));
  INV0 g2376(.A (hf[8]), .Q (n_176));
  CLKIN2 g2373(.A (Bist_count_N[3]), .Q (n_175));
  INV0 g2374(.A (hf[6]), .Q (n_174));
  INV0 g2375(.A (hf[20]), .Q (n_173));
  OAI222 g3129__2398(.A (n_171), .B (n_164), .C (n_169), .D
       (circuito_scan_fs_state[0]), .Q (out_sync_err_d));
  CLKIN3 g3130(.A (n_172), .Q (n_189));
  NOR40 g3131__5107(.A (n_134), .B (circuito_scan_fs_state[0]), .C
       (n_160), .D (n_167), .Q (n_172));
  OAI222 g3132__6260(.A (n_170), .B (n_150), .C (circuito_scan_n_10),
       .D (n_134), .Q (circuito_scan_n_19));
  AOI221 g3133__4319(.A (n_168), .B (n_149), .C
       (circuito_scan_fs_state[1]), .D (circuito_scan_fs_state[0]), .Q
       (n_171));
  CLKIN3 g3134(.A (circuito_scan_n_17), .Q (n_170));
  NOR21 g3135__8428(.A (RST), .B (n_168), .Q (circuito_scan_n_17));
  NAND31 g3136__5526(.A (n_164), .B (circuito_scan_fs_state[0]), .C
       (n_137), .Q (circuito_scan_n_10));
  NAND22 g3137__6783(.A (n_166), .B (n_134), .Q (n_169));
  AOI211 g3138__3680(.A (n_162), .B (n_161), .C
       (circuito_scan_fs_state[1]), .Q (n_167));
  NAND22 g3139__1617(.A (n_165), .B (n_132), .Q (n_168));
  INV2 g3140(.A (n_165), .Q (n_166));
  NOR21 g3141__2802(.A (n_161), .B (n_163), .Q (n_165));
  NOR21 g3142__1705(.A (n_160), .B (n_163), .Q (n_164));
  INV3 g3143(.A (n_163), .Q (n_162));
  OAI212 g3144__5122(.A (Bist_state[0]), .B (n_135), .C (n_159), .Q
       (bist_end));
  IMUX21 g3145__8246(.A (in_x2), .B (in_en), .S (n_188), .Q (n_163));
  IMUX21 g3146__7098(.A (in_x1), .B (in_j), .S (n_188), .Q (n_161));
  IMUX21 g3147__6131(.A (in_x0), .B (in_k), .S (n_188), .Q (n_160));
  DLQ3 Comp_passnfail_reg(.GN (Finish), .D (n_157), .Q (pass_fail));
  INV2 g3149(.A (n_183), .Q (n_159));
  OAI212 g3150__1881(.A (Bist_n_350), .B (n_185), .C (n_142), .Q
       (n_183));
  INV3 g3151(.A (n_158), .Q (n_188));
  NOR21 g3152__5115(.A (Bist_n_350), .B (n_182), .Q (n_158));
  NOR20 g3153__7482(.A (n_152), .B (n_156), .Q (n_157));
  NAND22 g3154__4733(.A (n_155), .B (n_187), .Q (n_185));
  NAND20 g3155__6161(.A (n_153), .B (n_154), .Q (n_156));
  NAND22 g3156__9315(.A (n_187), .B (n_186), .Q (n_182));
  INV2 g3157(.A (n_155), .Q (n_186));
  NOR40 g3158__9945(.A (Bist_count_M[1]), .B (Bist_count_M[0]), .C
       (n_133), .D (n_147), .Q (n_155));
  NAND33 g3159__2883(.A (n_146), .B (n_143), .C (Bist_count_N[0]), .Q
       (n_187));
  NOR40 g3160__2346(.A (hf[5]), .B (hf[0]), .C (hf[1]), .D (n_140), .Q
       (n_154));
  NOR40 g3161__1666(.A (hf[14]), .B (hf[7]), .C (n_145), .D (n_151), .Q
       (n_153));
  NAND40 g3162__7410(.A (n_148), .B (n_144), .C (hf[13]), .D (hf[12]),
       .Q (n_152));
  NAND40 g3163__6417(.A (hf[11]), .B (hf[18]), .C (hf[15]), .D
       (hf[19]), .Q (n_151));
  NAND22 g3164__5477(.A (n_141), .B (n_136), .Q (Finish));
  NAND31 g3165__2398(.A (n_135), .B (Bist_state[0]), .C
       (Bist_state[1]), .Q (Bist_n_350));
  INV2 g3166(.A (n_149), .Q (n_150));
  NOR40 g3167__5107(.A (hf[9]), .B (hf[4]), .C (n_176), .D (n_174), .Q
       (n_148));
  NAND41 g3168__6260(.A (n_139), .B (n_138), .C (Bist_count_M[2]), .D
       (Bist_count_M[5]), .Q (n_147));
  NOR40 g3169__4319(.A (Bist_count_N[4]), .B (Bist_count_N[2]), .C
       (Bist_count_N[1]), .D (n_175), .Q (n_146));
  IMUX21 g3170__8428(.A (n_134), .B (circuito_scan_fs_state[2]), .S
       (circuito_scan_fs_state[1]), .Q (n_149));
  NAND20 g3171__5526(.A (hf[17]), .B (hf[16]), .Q (n_145));
  NOR20 g3172__6783(.A (hf[10]), .B (hf[3]), .Q (n_144));
  NOR21 g3173__3680(.A (Bist_count_N[6]), .B (Bist_count_N[5]), .Q
       (n_143));
  INV2 g3174(.A (n_141), .Q (n_142));
  NAND20 g3175__1617(.A (n_173), .B (hf[2]), .Q (n_140));
  NAND22 g3176__2802(.A (n_135), .B (Bist_state[0]), .Q (n_184));
  NOR21 g3177__1705(.A (Bist_state[1]), .B (n_135), .Q (n_141));
  INV3 g3178(.A (Bist_count_M[3]), .Q (n_139));
  INV3 g3179(.A (Bist_count_M[4]), .Q (n_138));
  INV2 g3180(.A (RST), .Q (n_137));
  INV2 g3181(.A (Bist_state[0]), .Q (n_136));
  INV3 g3182(.A (Bist_state[2]), .Q (n_135));
  INV3 g3183(.A (circuito_scan_fs_state[2]), .Q (n_134));
  INV3 g3184(.A (Bist_count_M[6]), .Q (n_133));
  INV2 g3185(.A (circuito_scan_fs_state[0]), .Q (n_132));
  DFC3 \Bist_count_M_reg[0] (.RN (n_10), .C (CLK), .D (n_71), .Q
       (Bist_count_M[0]), .QN (UNCONNECTED));
  DFC3 \Bist_count_M_reg[1] (.RN (n_10), .C (CLK), .D (n_89), .Q
       (Bist_count_M[1]), .QN (UNCONNECTED0));
  DFC3 \Bist_count_M_reg[2] (.RN (n_10), .C (CLK), .D (n_104), .Q
       (Bist_count_M[2]), .QN (UNCONNECTED1));
  DFC3 \Bist_count_M_reg[3] (.RN (n_10), .C (CLK), .D (n_120), .Q
       (Bist_count_M[3]), .QN (UNCONNECTED2));
  DFC3 \Bist_count_M_reg[4] (.RN (n_10), .C (CLK), .D (n_124), .Q
       (Bist_count_M[4]), .QN (n_4));
  DFC3 \Bist_count_M_reg[5] (.RN (n_10), .C (CLK), .D (n_129), .Q
       (Bist_count_M[5]), .QN (n_6));
  DFC3 \Bist_count_M_reg[6] (.RN (n_10), .C (CLK), .D (n_131), .Q
       (Bist_count_M[6]), .QN (UNCONNECTED3));
  JKC3 \Bist_count_N_reg[0] (.RN (n_10), .C (CLK), .J (n_11), .K
       (n_20), .Q (Bist_count_N[0]), .QN (UNCONNECTED4));
  DFC3 \Bist_count_N_reg[1] (.RN (n_10), .C (CLK), .D (n_84), .Q
       (Bist_count_N[1]), .QN (n_8));
  DFC3 \Bist_count_N_reg[2] (.RN (n_10), .C (CLK), .D (n_98), .Q
       (Bist_count_N[2]), .QN (n_2));
  DFC3 \Bist_count_N_reg[3] (.RN (n_10), .C (CLK), .D (n_110), .Q
       (Bist_count_N[3]), .QN (UNCONNECTED5));
  DFC3 \Bist_count_N_reg[4] (.RN (n_10), .C (CLK), .D (n_115), .Q
       (Bist_count_N[4]), .QN (n_1));
  DFC3 \Bist_count_N_reg[5] (.RN (n_10), .C (CLK), .D (n_119), .Q
       (Bist_count_N[5]), .QN (n_7));
  DFC3 \Bist_count_N_reg[6] (.RN (n_10), .C (CLK), .D (n_118), .Q
       (Bist_count_N[6]), .QN (UNCONNECTED6));
  DFC3 \Bist_state_reg[0] (.RN (n_10), .C (CLK), .D (n_88), .Q
       (Bist_state[0]), .QN (UNCONNECTED7));
  DFC3 \Bist_state_reg[1] (.RN (n_10), .C (CLK), .D (n_78), .Q
       (Bist_state[1]), .QN (UNCONNECTED8));
  DFC3 \Bist_state_reg[2] (.RN (n_10), .C (CLK), .D (n_67), .Q
       (Bist_state[2]), .QN (UNCONNECTED9));
  DF3 LFSR_in_x0_reg(.C (CLK), .D (n_24), .Q (in_x0), .QN
       (UNCONNECTED10));
  DF3 LFSR_in_x1_reg(.C (CLK), .D (n_25), .Q (in_x1), .QN (n_9));
  DF3 LFSR_in_x2_reg(.C (CLK), .D (n_114), .Q (in_x2), .QN (n_3));
  DF3 MISR_h0_reg(.C (CLK), .D (n_63), .Q (MISR_h0), .QN
       (UNCONNECTED11));
  DF3 MISR_h1_reg(.C (CLK), .D (n_59), .Q (MISR_h1), .QN
       (UNCONNECTED12));
  DF3 MISR_h2_reg(.C (CLK), .D (n_62), .Q (MISR_h2), .QN
       (UNCONNECTED13));
  DF3 MISR_h3_reg(.C (CLK), .D (n_50), .Q (MISR_h3), .QN
       (UNCONNECTED14));
  DF3 MISR_h4_reg(.C (CLK), .D (n_55), .Q (MISR_h4), .QN
       (UNCONNECTED15));
  DF3 MISR_h5_reg(.C (CLK), .D (n_58), .Q (MISR_h5), .QN
       (UNCONNECTED16));
  DF3 MISR_h6_reg(.C (CLK), .D (n_54), .Q (MISR_h6), .QN
       (UNCONNECTED17));
  DF3 MISR_h7_reg(.C (CLK), .D (n_53), .Q (MISR_h7), .QN
       (UNCONNECTED18));
  DF3 MISR_h8_reg(.C (CLK), .D (n_57), .Q (MISR_h8), .QN
       (UNCONNECTED19));
  DF3 MISR_h9_reg(.C (CLK), .D (n_70), .Q (MISR_h9), .QN
       (UNCONNECTED20));
  DF3 MISR_h10_reg(.C (CLK), .D (n_69), .Q (MISR_h10), .QN
       (UNCONNECTED21));
  DF3 MISR_h11_reg(.C (CLK), .D (n_68), .Q (MISR_h11), .QN
       (UNCONNECTED22));
  DF3 MISR_h12_reg(.C (CLK), .D (n_61), .Q (MISR_h12), .QN
       (UNCONNECTED23));
  DF3 MISR_h13_reg(.C (CLK), .D (n_72), .Q (MISR_h13), .QN
       (UNCONNECTED24));
  DF3 MISR_h14_reg(.C (CLK), .D (n_66), .Q (MISR_h14), .QN
       (UNCONNECTED25));
  DF3 MISR_h15_reg(.C (CLK), .D (n_60), .Q (MISR_h15), .QN
       (UNCONNECTED26));
  DF3 MISR_h16_reg(.C (CLK), .D (n_65), .Q (MISR_h16), .QN
       (UNCONNECTED27));
  DF3 MISR_h17_reg(.C (CLK), .D (n_64), .Q (MISR_h17), .QN
       (UNCONNECTED28));
  DF3 MISR_h18_reg(.C (CLK), .D (n_80), .Q (MISR_h18), .QN (n_5));
  DF3 MISR_h19_reg(.C (CLK), .D (n_86), .Q (MISR_h19), .QN
       (UNCONNECTED29));
  DF3 MISR_h20_reg(.C (CLK), .D (n_83), .Q (MISR_h20), .QN
       (UNCONNECTED30));
  DFE1 \MISR_hf_reg[0] (.C (CLK), .D (MISR_h20), .E (n_17), .Q (hf[0]),
       .QN (UNCONNECTED31));
  DFE1 \MISR_hf_reg[1] (.C (CLK), .D (MISR_h19), .E (n_17), .Q (hf[1]),
       .QN (UNCONNECTED32));
  DFE1 \MISR_hf_reg[2] (.C (CLK), .D (MISR_h18), .E (n_17), .Q (hf[2]),
       .QN (UNCONNECTED33));
  DFE1 \MISR_hf_reg[3] (.C (CLK), .D (MISR_h17), .E (n_17), .Q (hf[3]),
       .QN (UNCONNECTED34));
  DFE1 \MISR_hf_reg[4] (.C (CLK), .D (MISR_h16), .E (n_17), .Q (hf[4]),
       .QN (UNCONNECTED35));
  DFE1 \MISR_hf_reg[5] (.C (CLK), .D (MISR_h15), .E (n_17), .Q (hf[5]),
       .QN (UNCONNECTED36));
  DFE1 \MISR_hf_reg[6] (.C (CLK), .D (MISR_h14), .E (n_17), .Q (hf[6]),
       .QN (UNCONNECTED37));
  DFE1 \MISR_hf_reg[7] (.C (CLK), .D (MISR_h13), .E (n_17), .Q (hf[7]),
       .QN (UNCONNECTED38));
  DFE1 \MISR_hf_reg[8] (.C (CLK), .D (MISR_h12), .E (n_17), .Q (hf[8]),
       .QN (UNCONNECTED39));
  DFE1 \MISR_hf_reg[9] (.C (CLK), .D (MISR_h11), .E (n_17), .Q (hf[9]),
       .QN (UNCONNECTED40));
  DFE1 \MISR_hf_reg[10] (.C (CLK), .D (MISR_h10), .E (n_17), .Q
       (hf[10]), .QN (UNCONNECTED41));
  DFE1 \MISR_hf_reg[11] (.C (CLK), .D (MISR_h9), .E (n_17), .Q
       (hf[11]), .QN (UNCONNECTED42));
  DFE1 \MISR_hf_reg[12] (.C (CLK), .D (MISR_h8), .E (n_17), .Q
       (hf[12]), .QN (UNCONNECTED43));
  DFE1 \MISR_hf_reg[13] (.C (CLK), .D (MISR_h7), .E (n_17), .Q
       (hf[13]), .QN (UNCONNECTED44));
  DFE1 \MISR_hf_reg[14] (.C (CLK), .D (MISR_h6), .E (n_17), .Q
       (hf[14]), .QN (UNCONNECTED45));
  DFE1 \MISR_hf_reg[15] (.C (CLK), .D (MISR_h5), .E (n_17), .Q
       (hf[15]), .QN (UNCONNECTED46));
  DFE1 \MISR_hf_reg[16] (.C (CLK), .D (MISR_h4), .E (n_17), .Q
       (hf[16]), .QN (UNCONNECTED47));
  DFE1 \MISR_hf_reg[17] (.C (CLK), .D (MISR_h3), .E (n_17), .Q
       (hf[17]), .QN (UNCONNECTED48));
  DFE1 \MISR_hf_reg[18] (.C (CLK), .D (MISR_h2), .E (n_17), .Q
       (hf[18]), .QN (UNCONNECTED49));
  DFE1 \MISR_hf_reg[19] (.C (CLK), .D (MISR_h1), .E (n_17), .Q
       (hf[19]), .QN (UNCONNECTED50));
  DFE1 \MISR_hf_reg[20] (.C (CLK), .D (MISR_h0), .E (n_17), .Q
       (hf[20]), .QN (UNCONNECTED51));
  NOR21 g3638__5122(.A (n_13), .B (n_130), .Q (n_131));
  IMUX21 g3640__8246(.A (n_127), .B (Bist_count_M[6]), .S (n_187), .Q
       (n_130));
  NOR21 g3641__7098(.A (n_13), .B (n_128), .Q (n_129));
  IMUX21 g3642__6131(.A (n_126), .B (Bist_count_M[5]), .S (n_187), .Q
       (n_128));
  XOR21 g3643__1881(.A (Bist_count_M[6]), .B (n_125), .Q (n_127));
  ADD22 g3645__5115(.A (n_121), .B (Bist_count_M[5]), .CO (n_125), .S
       (n_126));
  IMUX21 g3647__7482(.A (n_122), .B (Bist_count_M[4]), .S (n_187), .Q
       (n_123));
  ADD22 g3651__4733(.A (n_107), .B (Bist_count_M[4]), .CO (n_121), .S
       (n_122));
  OAI311 g3655__6161(.A (Bist_count_N[5]), .B (n_188), .C (n_101), .D
       (n_116), .Q (n_119));
  OAI212 g3656__9315(.A (n_188), .B (n_109), .C (n_117), .Q (n_118));
  NAND22 g3657__9945(.A (n_111), .B (Bist_count_N[6]), .Q (n_117));
  NAND22 g3658__2883(.A (n_111), .B (Bist_count_N[5]), .Q (n_116));
  CLKIN2 g3660(.A (n_113), .Q (n_115));
  OAI2111 g3661__2346(.A (in_x0), .B (n_99), .C (n_105), .D (n_10), .Q
       (n_114));
  AOI221 g3662__1666(.A (n_103), .B (n_11), .C (n_102), .D
       (Bist_count_N[4]), .Q (n_113));
  IMUX21 g3663__7410(.A (n_108), .B (Bist_count_M[3]), .S (n_187), .Q
       (n_112));
  OAI212 g3664__6417(.A (n_188), .B (n_100), .C (n_20), .Q (n_111));
  OAI311 g3666__5477(.A (Bist_count_N[3]), .B (n_93), .C (n_188), .D
       (n_106), .Q (n_110));
  AOI221 g3667__2398(.A (n_100), .B (n_15), .C (n_7), .D
       (Bist_count_N[6]), .Q (n_109));
  ADD22 g3668__5107(.A (n_90), .B (Bist_count_M[3]), .CO (n_107), .S
       (n_108));
  NAND22 g3669__6260(.A (n_102), .B (Bist_count_N[3]), .Q (n_106));
  NAND22 g3671__4319(.A (n_99), .B (in_x0), .Q (n_105));
  NOR21 g3672__8428(.A (n_13), .B (n_97), .Q (n_104));
  IMUX21 g3673__5526(.A (n_96), .B (Bist_count_N[3]), .S
       (Bist_count_N[4]), .Q (n_103));
  INV2 g3674(.A (n_100), .Q (n_101));
  OAI212 g3675__6783(.A (n_94), .B (n_188), .C (n_20), .Q (n_102));
  NOR21 g3676__3680(.A (n_1), .B (n_96), .Q (n_100));
  OAI222 g3677__1617(.A (n_188), .B (n_95), .C (n_20), .D (n_2), .Q
       (n_98));
  IMUX21 g3678__2802(.A (n_91), .B (Bist_count_M[2]), .S (n_187), .Q
       (n_97));
  IMUX21 g3679__1705(.A (in_x2), .B (in_x1), .S (n_87), .Q (n_99));
  NAND22 g3681__5122(.A (n_94), .B (Bist_count_N[3]), .Q (n_96));
  INV2 g3683(.A (n_92), .Q (n_95));
  INV2 g3684(.A (n_94), .Q (n_93));
  ADD22 g3685__8246(.A (n_73), .B (Bist_count_N[2]), .CO (n_94), .S
       (n_92));
  ADD22 g3686__7098(.A (n_75), .B (Bist_count_M[2]), .CO (n_90), .S
       (n_91));
  NAND22 g3691__6131(.A (n_21), .B (n_85), .Q (n_88));
  AOI311 g3692__1881(.A (n_6), .B (n_4), .C (n_52), .D (n_188), .Q
       (n_87));
  NAND22 g3693__5115(.A (n_81), .B (n_10), .Q (n_86));
  AOI211 g3696__7482(.A (Bist_state[2]), .B (n_36), .C (n_79), .Q
       (n_85));
  OAI222 g3697__4733(.A (n_188), .B (n_77), .C (n_20), .D (n_8), .Q
       (n_84));
  OAI2111 g3698__6161(.A (n_28), .B (bist_end), .C (n_26), .D (n_10),
       .Q (n_83));
  IMUX20 g3699__9315(.A (n_76), .B (Bist_count_M[1]), .S (n_187), .Q
       (n_82));
  IMUX21 g3723__9945(.A (n_43), .B (MISR_h19), .S (bist_end), .Q
       (n_81));
  OAI222 g3724__2883(.A (n_27), .B (n_19), .C (n_5), .D (n_17), .Q
       (n_80));
  OAI212 g3725__2346(.A (n_36), .B (Bist_state[2]), .C (Finish), .Q
       (n_79));
  NAND22 g3726__1666(.A (n_51), .B (n_45), .Q (n_78));
  INV2 g3746(.A (n_74), .Q (n_77));
  ADD22 g3747__7410(.A (Bist_count_M[1]), .B (Bist_count_M[0]), .CO
       (n_75), .S (n_76));
  ADD22 g3748__6417(.A (Bist_count_N[1]), .B (Bist_count_N[0]), .CO
       (n_73), .S (n_74));
  NAND22 g3749__5477(.A (n_39), .B (n_10), .Q (n_72));
  NOR21 g3750__2398(.A (n_13), .B (n_0), .Q (n_71));
  NAND22 g3751__5107(.A (n_42), .B (n_10), .Q (n_70));
  NAND22 g3752__6260(.A (n_41), .B (n_10), .Q (n_69));
  NAND22 g3753__4319(.A (n_44), .B (n_10), .Q (n_68));
  NAND22 g3754__8428(.A (n_179), .B (n_40), .Q (n_67));
  NAND22 g3755__5526(.A (n_38), .B (n_10), .Q (n_66));
  NAND22 g3756__6783(.A (n_37), .B (n_10), .Q (n_65));
  NAND22 g3757__3680(.A (n_30), .B (n_10), .Q (n_64));
  NAND22 g3758__1617(.A (n_34), .B (n_10), .Q (n_63));
  NAND22 g3759__2802(.A (n_33), .B (n_10), .Q (n_62));
  INV2 g3760(.A (n_56), .Q (n_61));
  INV2 g3761(.A (n_49), .Q (n_60));
  INV2 g3762(.A (n_48), .Q (n_59));
  INV2 g3763(.A (n_47), .Q (n_58));
  INV2 g3764(.A (n_46), .Q (n_57));
  AOI221 g3765__1705(.A (MISR_h13), .B (n_18), .C (MISR_h12), .D
       (n_16), .Q (n_56));
  NAND22 g3766__5122(.A (n_31), .B (n_10), .Q (n_55));
  NAND22 g3767__8246(.A (n_35), .B (n_10), .Q (n_54));
  NAND22 g3768__7098(.A (n_29), .B (n_10), .Q (n_53));
  AOI311 g3769__6131(.A (Bist_count_M[2]), .B (Bist_count_M[1]), .C
       (Bist_count_M[3]), .D (Bist_count_M[6]), .Q (n_52));
  AOI311 g3770__1881(.A (n_14), .B (Bist_state[0]), .C (Bist_state[2]),
       .D (n_22), .Q (n_51));
  NAND22 g3771__5115(.A (n_32), .B (n_10), .Q (n_50));
  AOI221 g3772__7482(.A (MISR_h16), .B (n_18), .C (MISR_h15), .D
       (n_16), .Q (n_49));
  AOI221 g3773__4733(.A (MISR_h2), .B (n_18), .C (MISR_h1), .D (n_16),
       .Q (n_48));
  AOI221 g3774__6161(.A (MISR_h6), .B (n_18), .C (MISR_h5), .D (n_16),
       .Q (n_47));
  AOI221 g3775__9315(.A (MISR_h9), .B (n_18), .C (MISR_h8), .D (n_16),
       .Q (n_46));
  AOI221 g3776__9945(.A (n_23), .B (bist_start), .C (n_184), .D
       (Bist_state[1]), .Q (n_45));
  IMUX20 g3777__2883(.A (MISR_h12), .B (MISR_h11), .S (bist_end), .Q
       (n_44));
  IMUX21 g3778__2346(.A (MISR_h18), .B (n_5), .S (n_189), .Q (n_43));
  IMUX20 g3779__1666(.A (MISR_h10), .B (MISR_h9), .S (bist_end), .Q
       (n_42));
  IMUX20 g3780__7410(.A (MISR_h11), .B (MISR_h10), .S (bist_end), .Q
       (n_41));
  OAI212 g3781__6417(.A (n_14), .B (Bist_state[0]), .C (Bist_state[2]),
       .Q (n_40));
  IMUX20 g3782__5477(.A (MISR_h14), .B (MISR_h13), .S (bist_end), .Q
       (n_39));
  IMUX20 g3783__2398(.A (MISR_h15), .B (MISR_h14), .S (bist_end), .Q
       (n_38));
  IMUX20 g3784__5107(.A (MISR_h17), .B (MISR_h16), .S (bist_end), .Q
       (n_37));
  IMUX20 g3787__6260(.A (MISR_h7), .B (MISR_h6), .S (bist_end), .Q
       (n_35));
  IMUX20 g3788__4319(.A (MISR_h1), .B (MISR_h0), .S (bist_end), .Q
       (n_34));
  IMUX20 g3789__8428(.A (MISR_h3), .B (MISR_h2), .S (bist_end), .Q
       (n_33));
  IMUX20 g3790__5526(.A (MISR_h4), .B (MISR_h3), .S (bist_end), .Q
       (n_32));
  IMUX20 g3791__6783(.A (MISR_h5), .B (MISR_h4), .S (bist_end), .Q
       (n_31));
  IMUX20 g3792__3680(.A (MISR_h18), .B (MISR_h17), .S (bist_end), .Q
       (n_30));
  IMUX20 g3793__1617(.A (MISR_h8), .B (MISR_h7), .S (bist_end), .Q
       (n_29));
  XNR21 g3795__2802(.A (scan_out), .B (MISR_h19), .Q (n_28));
  XNR21 g3796__1705(.A (out_sync_err_d), .B (MISR_h17), .Q (n_27));
  MUX22 g3797__5122(.A (bist_start), .B (Bist_state[0]), .S
       (Bist_state[1]), .Q (n_36));
  NAND22 g3798__8246(.A (bist_end), .B (MISR_h20), .Q (n_26));
  NAND22 g3799__7098(.A (n_3), .B (n_10), .Q (n_25));
  NAND22 g3800__6131(.A (n_9), .B (n_10), .Q (n_24));
  NOR21 g3801__1881(.A (Bist_state[1]), .B (n_184), .Q (n_23));
  CLKIN2 g3802(.A (n_21), .Q (n_22));
  INV2 g3803(.A (n_18), .Q (n_19));
  INV3 g3804(.A (n_17), .Q (n_16));
  NOR21 g3805__5115(.A (Bist_count_N[6]), .B (n_7), .Q (n_15));
  NAND22 g3806__7482(.A (n_185), .B (n_12), .Q (n_21));
  NAND22 g3807__4733(.A (n_177), .B (Bist_n_350), .Q (n_20));
  NOR21 g3808__6161(.A (RST), .B (bist_end), .Q (n_18));
  NAND22 g3809__9315(.A (bist_end), .B (n_10), .Q (n_17));
  INV2 g3812(.A (bist_start), .Q (n_14));
  INV3 g3836(.A (n_186), .Q (n_13));
  INV2 g3837(.A (Bist_n_350), .Q (n_12));
  INV2 g3860(.A (n_188), .Q (n_11));
  INV3 g3862(.A (RST), .Q (n_10));
  XOR21 g2__9945(.A (n_187), .B (Bist_count_M[0]), .Q (n_0));
  INV0 g3863(.A (n_123), .Q (n_124));
  INV0 g3864(.A (n_112), .Q (n_120));
  INV0 g3865(.A (n_82), .Q (n_89));
endmodule

